CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Companions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Role" text NOT NULL,
    "Group" text NOT NULL,
    "Contact" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Companions" PRIMARY KEY ("Id")
);

CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "JobTitle" text NOT NULL,
    "Company" text NOT NULL,
    "Type" text NOT NULL,
    "Contact" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id")
);

CREATE TABLE "Equipments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Manufacturer" text NOT NULL,
    "Model" text NOT NULL,
    "SerialNumber" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Equipments" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Address" text NOT NULL,
    "ART" text NOT NULL,
    "Group" text NOT NULL,
    "Status" text NOT NULL,
    "Manager" text NOT NULL,
    "ContractType" text NOT NULL,
    "Client" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "ExpectedEndDate" timestamp with time zone,
    "ImagePath" text,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Profile" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "ProjectMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProjectMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectMembers_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CompanionId" integer,
    "Number" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "CheckInTime" text NOT NULL,
    "CheckOutTime" text NOT NULL,
    "BreakTime" text NOT NULL,
    "GeneralNotes" text NOT NULL,
    "Status" text NOT NULL,
    "IsSynced" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsDraft" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Reports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reports_Companions_CompanionId" FOREIGN KEY ("CompanionId") REFERENCES "Companions" ("Id"),
    CONSTRAINT "FK_Reports_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reports_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Activities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "Description" text NOT NULL,
    "Location" text NOT NULL,
    "Status" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Activities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Activities_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmployeePresences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "EmployeeName" text NOT NULL,
    "JobTitle" text NOT NULL,
    "HoursWorked" integer NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_EmployeePresences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmployeePresences_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Materials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "Name" text NOT NULL,
    "Quantity" text NOT NULL,
    "Unit" text NOT NULL,
    "Type" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Materials" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Materials_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Occurrences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "Description" text NOT NULL,
    "Tags" text NOT NULL,
    "StartTime" text NOT NULL,
    "EndTime" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Occurrences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Occurrences_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Photos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "FilePath" text NOT NULL,
    "Caption" text NOT NULL,
    "RelatedActivity" text NOT NULL,
    "TakenAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Photos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Photos_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReportCompanions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "CompanionId" integer NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ReportCompanions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReportCompanions_Companions_CompanionId" FOREIGN KEY ("CompanionId") REFERENCES "Companions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReportCompanions_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReportEquipments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "EquipmentId" integer NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ReportEquipments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReportEquipments_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReportEquipments_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Signatures" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "SignerName" text NOT NULL,
    "Role" text NOT NULL,
    "CPF" text NOT NULL,
    "SignedAt" timestamp with time zone,
    "IsSigned" boolean NOT NULL,
    "EmployeeId" integer,
    "CheckInTime" text NOT NULL,
    "CheckOutTime" text NOT NULL,
    "BreakTime" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Signatures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Signatures_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WeatherDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportId" integer NOT NULL,
    "Period" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "Weather" text NOT NULL,
    "Condition" text NOT NULL,
    "RainfallIndex" double precision NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_WeatherDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WeatherDetails_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Activities_ReportId" ON "Activities" ("ReportId");

CREATE INDEX "IX_EmployeePresences_ReportId" ON "EmployeePresences" ("ReportId");

CREATE INDEX "IX_Materials_ReportId" ON "Materials" ("ReportId");

CREATE INDEX "IX_Occurrences_ReportId" ON "Occurrences" ("ReportId");

CREATE INDEX "IX_Photos_ReportId" ON "Photos" ("ReportId");

CREATE INDEX "IX_ProjectMembers_ProjectId" ON "ProjectMembers" ("ProjectId");

CREATE INDEX "IX_ProjectMembers_UserId" ON "ProjectMembers" ("UserId");

CREATE INDEX "IX_ReportCompanions_CompanionId" ON "ReportCompanions" ("CompanionId");

CREATE INDEX "IX_ReportCompanions_ReportId" ON "ReportCompanions" ("ReportId");

CREATE INDEX "IX_ReportEquipments_EquipmentId" ON "ReportEquipments" ("EquipmentId");

CREATE INDEX "IX_ReportEquipments_ReportId" ON "ReportEquipments" ("ReportId");

CREATE INDEX "IX_Reports_CompanionId" ON "Reports" ("CompanionId");

CREATE INDEX "IX_Reports_ProjectId" ON "Reports" ("ProjectId");

CREATE INDEX "IX_Reports_UserId" ON "Reports" ("UserId");

CREATE INDEX "IX_Signatures_ReportId" ON "Signatures" ("ReportId");

CREATE INDEX "IX_WeatherDetails_ReportId" ON "WeatherDetails" ("ReportId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260409180159_InitialCreate', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Activities" DROP CONSTRAINT "FK_Activities_Reports_ReportId";

ALTER TABLE "EmployeePresences" DROP CONSTRAINT "FK_EmployeePresences_Reports_ReportId";

ALTER TABLE "Materials" DROP CONSTRAINT "FK_Materials_Reports_ReportId";

ALTER TABLE "Occurrences" DROP CONSTRAINT "FK_Occurrences_Reports_ReportId";

ALTER TABLE "Photos" DROP CONSTRAINT "FK_Photos_Reports_ReportId";

ALTER TABLE "ProjectMembers" DROP CONSTRAINT "FK_ProjectMembers_Projects_ProjectId";

ALTER TABLE "ProjectMembers" DROP CONSTRAINT "FK_ProjectMembers_Users_UserId";

ALTER TABLE "ReportCompanions" DROP CONSTRAINT "FK_ReportCompanions_Companions_CompanionId";

ALTER TABLE "ReportCompanions" DROP CONSTRAINT "FK_ReportCompanions_Reports_ReportId";

ALTER TABLE "ReportEquipments" DROP CONSTRAINT "FK_ReportEquipments_Equipments_EquipmentId";

ALTER TABLE "ReportEquipments" DROP CONSTRAINT "FK_ReportEquipments_Reports_ReportId";

ALTER TABLE "Reports" DROP CONSTRAINT "FK_Reports_Companions_CompanionId";

ALTER TABLE "Reports" DROP CONSTRAINT "FK_Reports_Projects_ProjectId";

ALTER TABLE "Reports" DROP CONSTRAINT "FK_Reports_Users_UserId";

ALTER TABLE "Signatures" DROP CONSTRAINT "FK_Signatures_Reports_ReportId";

ALTER TABLE "WeatherDetails" DROP CONSTRAINT "FK_WeatherDetails_Reports_ReportId";

ALTER TABLE "WeatherDetails" DROP CONSTRAINT "PK_WeatherDetails";

ALTER TABLE "Users" DROP CONSTRAINT "PK_Users";

ALTER TABLE "Signatures" DROP CONSTRAINT "PK_Signatures";

ALTER TABLE "Reports" DROP CONSTRAINT "PK_Reports";

ALTER TABLE "ReportEquipments" DROP CONSTRAINT "PK_ReportEquipments";

ALTER TABLE "ReportCompanions" DROP CONSTRAINT "PK_ReportCompanions";

ALTER TABLE "Projects" DROP CONSTRAINT "PK_Projects";

ALTER TABLE "ProjectMembers" DROP CONSTRAINT "PK_ProjectMembers";

ALTER TABLE "Photos" DROP CONSTRAINT "PK_Photos";

ALTER TABLE "Occurrences" DROP CONSTRAINT "PK_Occurrences";

ALTER TABLE "Materials" DROP CONSTRAINT "PK_Materials";

ALTER TABLE "Equipments" DROP CONSTRAINT "PK_Equipments";

ALTER TABLE "Employees" DROP CONSTRAINT "PK_Employees";

ALTER TABLE "EmployeePresences" DROP CONSTRAINT "PK_EmployeePresences";

ALTER TABLE "Companions" DROP CONSTRAINT "PK_Companions";

ALTER TABLE "Activities" DROP CONSTRAINT "PK_Activities";

ALTER TABLE "WeatherDetails" RENAME TO "WeatherDetail";

ALTER TABLE "Users" RENAME TO "User";

ALTER TABLE "Signatures" RENAME TO "Signature";

ALTER TABLE "Reports" RENAME TO "Report";

ALTER TABLE "ReportEquipments" RENAME TO "ReportEquipment";

ALTER TABLE "ReportCompanions" RENAME TO "ReportCompanion";

ALTER TABLE "Projects" RENAME TO "Project";

ALTER TABLE "ProjectMembers" RENAME TO "ProjectMember";

ALTER TABLE "Photos" RENAME TO "Photo";

ALTER TABLE "Occurrences" RENAME TO "Occurrence";

ALTER TABLE "Materials" RENAME TO "Material";

ALTER TABLE "Equipments" RENAME TO "Equipment";

ALTER TABLE "Employees" RENAME TO "Employee";

ALTER TABLE "EmployeePresences" RENAME TO "EmployeePresence";

ALTER TABLE "Companions" RENAME TO "Companion";

ALTER TABLE "Activities" RENAME TO "Activity";

ALTER INDEX "IX_WeatherDetails_ReportId" RENAME TO "IX_WeatherDetail_ReportId";

ALTER INDEX "IX_Signatures_ReportId" RENAME TO "IX_Signature_ReportId";

ALTER INDEX "IX_Reports_UserId" RENAME TO "IX_Report_UserId";

ALTER INDEX "IX_Reports_ProjectId" RENAME TO "IX_Report_ProjectId";

ALTER INDEX "IX_Reports_CompanionId" RENAME TO "IX_Report_CompanionId";

ALTER INDEX "IX_ReportEquipments_ReportId" RENAME TO "IX_ReportEquipment_ReportId";

ALTER INDEX "IX_ReportEquipments_EquipmentId" RENAME TO "IX_ReportEquipment_EquipmentId";

ALTER INDEX "IX_ReportCompanions_ReportId" RENAME TO "IX_ReportCompanion_ReportId";

ALTER INDEX "IX_ReportCompanions_CompanionId" RENAME TO "IX_ReportCompanion_CompanionId";

ALTER INDEX "IX_ProjectMembers_UserId" RENAME TO "IX_ProjectMember_UserId";

ALTER INDEX "IX_ProjectMembers_ProjectId" RENAME TO "IX_ProjectMember_ProjectId";

ALTER INDEX "IX_Photos_ReportId" RENAME TO "IX_Photo_ReportId";

ALTER INDEX "IX_Occurrences_ReportId" RENAME TO "IX_Occurrence_ReportId";

ALTER INDEX "IX_Materials_ReportId" RENAME TO "IX_Material_ReportId";

ALTER INDEX "IX_EmployeePresences_ReportId" RENAME TO "IX_EmployeePresence_ReportId";

ALTER INDEX "IX_Activities_ReportId" RENAME TO "IX_Activity_ReportId";

ALTER TABLE "WeatherDetail" ADD "Ativo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "WeatherDetail" ADD "Condicao" text NOT NULL DEFAULT '';

ALTER TABLE "WeatherDetail" ADD "IndicePluviometrico" double precision NOT NULL DEFAULT 0.0;

ALTER TABLE "WeatherDetail" ADD "Periodo" text NOT NULL DEFAULT '';

ALTER TABLE "WeatherDetail" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "WeatherDetail" ADD "Tempo" text NOT NULL DEFAULT '';

ALTER TABLE "User" ADD "Ativo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "User" ADD "Nome" text NOT NULL DEFAULT '';

ALTER TABLE "User" ADD "Perfil" text NOT NULL DEFAULT '';

ALTER TABLE "User" ADD "SenhaHash" text NOT NULL DEFAULT '';

ALTER TABLE "Signature" ALTER COLUMN "CPF" DROP NOT NULL;

ALTER TABLE "Signature" ADD "Assinado" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Signature" ADD "Cargo" text NOT NULL DEFAULT '';

ALTER TABLE "Signature" ADD "DataAssinatura" timestamp with time zone;

ALTER TABLE "Signature" ADD "FuncionarioId" integer;

ALTER TABLE "Signature" ADD "HoraEntrada" text NOT NULL DEFAULT '';

ALTER TABLE "Signature" ADD "HoraIntervalo" text NOT NULL DEFAULT '';

ALTER TABLE "Signature" ADD "HoraSaida" text NOT NULL DEFAULT '';

ALTER TABLE "Signature" ADD "NomeAssinante" text NOT NULL DEFAULT '';

ALTER TABLE "Signature" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Report" ADD "AcompanhanteId" integer;

ALTER TABLE "Report" ADD "CriadoEm" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Report" ADD "Data" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Report" ADD "HoraEntrada" text NOT NULL DEFAULT '';

ALTER TABLE "Report" ADD "HoraIntervalo" text NOT NULL DEFAULT '';

ALTER TABLE "Report" ADD "HoraSaida" text NOT NULL DEFAULT '';

ALTER TABLE "Report" ADD "Numero" integer NOT NULL DEFAULT 0;

ALTER TABLE "Report" ADD "ObraId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Report" ADD "ObsGerais" text NOT NULL DEFAULT '';

ALTER TABLE "Report" ADD "Rascunho" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Report" ADD "Sincronizado" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Report" ADD "UsuarioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "ReportEquipment" ADD "EquipamentoCadastradoId" integer NOT NULL DEFAULT 0;

ALTER TABLE "ReportEquipment" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "ReportCompanion" ADD "AcompanhanteId" integer NOT NULL DEFAULT 0;

ALTER TABLE "ReportCompanion" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Project" ADD "Ativo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Project" ADD "Contratante" text NOT NULL DEFAULT '';

ALTER TABLE "Project" ADD "DataInicio" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Project" ADD "Endereco" text NOT NULL DEFAULT '';

ALTER TABLE "Project" ADD "Grupo" text NOT NULL DEFAULT '';

ALTER TABLE "Project" ADD "ImagemPath" text;

ALTER TABLE "Project" ADD "Nome" text NOT NULL DEFAULT '';

ALTER TABLE "Project" ADD "PrevisaoTermino" timestamp with time zone;

ALTER TABLE "Project" ADD "Responsavel" text NOT NULL DEFAULT '';

ALTER TABLE "Project" ADD "TipoContrato" text NOT NULL DEFAULT '';

ALTER TABLE "ProjectMember" ADD "ObraId" integer NOT NULL DEFAULT 0;

ALTER TABLE "ProjectMember" ADD "Papel" text NOT NULL DEFAULT '';

ALTER TABLE "ProjectMember" ADD "UsuarioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Photo" ADD "AtividadeRelacionada" text NOT NULL DEFAULT '';

ALTER TABLE "Photo" ADD "CaminhoArquivo" text NOT NULL DEFAULT '';

ALTER TABLE "Photo" ADD "Legenda" text NOT NULL DEFAULT '';

ALTER TABLE "Photo" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Photo" ADD "TiradaEm" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Occurrence" ADD "Descricao" text NOT NULL DEFAULT '';

ALTER TABLE "Occurrence" ADD "HoraFim" text NOT NULL DEFAULT '';

ALTER TABLE "Occurrence" ADD "HoraInicio" text NOT NULL DEFAULT '';

ALTER TABLE "Occurrence" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Material" ADD "Nome" text NOT NULL DEFAULT '';

ALTER TABLE "Material" ADD "Quantidade" text NOT NULL DEFAULT '';

ALTER TABLE "Material" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Material" ADD "Tipo" text NOT NULL DEFAULT '';

ALTER TABLE "Material" ADD "Unidade" text NOT NULL DEFAULT '';

ALTER TABLE "Equipment" ADD "Ativo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Equipment" ADD "Fabricante" text NOT NULL DEFAULT '';

ALTER TABLE "Equipment" ADD "Modelo" text NOT NULL DEFAULT '';

ALTER TABLE "Equipment" ADD "Nome" text NOT NULL DEFAULT '';

ALTER TABLE "Equipment" ADD "NumeroSerie" text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD "Ativo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Employee" ADD "Contato" text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD "Empresa" text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD "Funcao" text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD "Nome" text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD "Tipo" text NOT NULL DEFAULT '';

ALTER TABLE "EmployeePresence" ADD "Funcao" text NOT NULL DEFAULT '';

ALTER TABLE "EmployeePresence" ADD "HorasTrabalhadas" integer NOT NULL DEFAULT 0;

ALTER TABLE "EmployeePresence" ADD "NomeFuncionario" text NOT NULL DEFAULT '';

ALTER TABLE "EmployeePresence" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Companion" ADD "Ativo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Companion" ADD "Cargo" text NOT NULL DEFAULT '';

ALTER TABLE "Companion" ADD "Contato" text NOT NULL DEFAULT '';

ALTER TABLE "Companion" ADD "Grupo" text NOT NULL DEFAULT '';

ALTER TABLE "Companion" ADD "Nome" text NOT NULL DEFAULT '';

ALTER TABLE "Activity" ADD "Descricao" text NOT NULL DEFAULT '';

ALTER TABLE "Activity" ADD "Local" text NOT NULL DEFAULT '';

ALTER TABLE "Activity" ADD "RelatorioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "WeatherDetail" ADD CONSTRAINT "PK_WeatherDetail" PRIMARY KEY ("Id");

ALTER TABLE "User" ADD CONSTRAINT "PK_User" PRIMARY KEY ("Id");

ALTER TABLE "Signature" ADD CONSTRAINT "PK_Signature" PRIMARY KEY ("Id");

ALTER TABLE "Report" ADD CONSTRAINT "PK_Report" PRIMARY KEY ("Id");

ALTER TABLE "ReportEquipment" ADD CONSTRAINT "PK_ReportEquipment" PRIMARY KEY ("Id");

ALTER TABLE "ReportCompanion" ADD CONSTRAINT "PK_ReportCompanion" PRIMARY KEY ("Id");

ALTER TABLE "Project" ADD CONSTRAINT "PK_Project" PRIMARY KEY ("Id");

ALTER TABLE "ProjectMember" ADD CONSTRAINT "PK_ProjectMember" PRIMARY KEY ("Id");

ALTER TABLE "Photo" ADD CONSTRAINT "PK_Photo" PRIMARY KEY ("Id");

ALTER TABLE "Occurrence" ADD CONSTRAINT "PK_Occurrence" PRIMARY KEY ("Id");

ALTER TABLE "Material" ADD CONSTRAINT "PK_Material" PRIMARY KEY ("Id");

ALTER TABLE "Equipment" ADD CONSTRAINT "PK_Equipment" PRIMARY KEY ("Id");

ALTER TABLE "Employee" ADD CONSTRAINT "PK_Employee" PRIMARY KEY ("Id");

ALTER TABLE "EmployeePresence" ADD CONSTRAINT "PK_EmployeePresence" PRIMARY KEY ("Id");

ALTER TABLE "Companion" ADD CONSTRAINT "PK_Companion" PRIMARY KEY ("Id");

ALTER TABLE "Activity" ADD CONSTRAINT "PK_Activity" PRIMARY KEY ("Id");

ALTER TABLE "Activity" ADD CONSTRAINT "FK_Activity_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "EmployeePresence" ADD CONSTRAINT "FK_EmployeePresence_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "Material" ADD CONSTRAINT "FK_Material_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "Occurrence" ADD CONSTRAINT "FK_Occurrence_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "Photo" ADD CONSTRAINT "FK_Photo_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "ProjectMember" ADD CONSTRAINT "FK_ProjectMember_Project_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Project" ("Id") ON DELETE CASCADE;

ALTER TABLE "ProjectMember" ADD CONSTRAINT "FK_ProjectMember_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE;

ALTER TABLE "Report" ADD CONSTRAINT "FK_Report_Companion_CompanionId" FOREIGN KEY ("CompanionId") REFERENCES "Companion" ("Id");

ALTER TABLE "Report" ADD CONSTRAINT "FK_Report_Project_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Project" ("Id") ON DELETE CASCADE;

ALTER TABLE "Report" ADD CONSTRAINT "FK_Report_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE;

ALTER TABLE "ReportCompanion" ADD CONSTRAINT "FK_ReportCompanion_Companion_CompanionId" FOREIGN KEY ("CompanionId") REFERENCES "Companion" ("Id") ON DELETE CASCADE;

ALTER TABLE "ReportCompanion" ADD CONSTRAINT "FK_ReportCompanion_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "ReportEquipment" ADD CONSTRAINT "FK_ReportEquipment_Equipment_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES "Equipment" ("Id") ON DELETE CASCADE;

ALTER TABLE "ReportEquipment" ADD CONSTRAINT "FK_ReportEquipment_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "Signature" ADD CONSTRAINT "FK_Signature_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

ALTER TABLE "WeatherDetail" ADD CONSTRAINT "FK_WeatherDetail_Report_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Report" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410132443_TornarCPFOpcional', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "SyncQueue" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityName" text NOT NULL,
    "EntityId" integer NOT NULL,
    "Operation" integer NOT NULL,
    "Payload" text NOT NULL,
    "PayloadVersion" integer NOT NULL,
    "Status" integer NOT NULL,
    "RetryCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastAttemptAt" timestamp with time zone,
    "LastError" text,
    "EventId" text NOT NULL,
    "DeviceId" text NOT NULL,
    CONSTRAINT "PK_SyncQueue" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_SyncQueue_EntityName_EntityId" ON "SyncQueue" ("EntityName", "EntityId");

CREATE UNIQUE INDEX "IX_SyncQueue_EventId" ON "SyncQueue" ("EventId");

CREATE INDEX "IX_SyncQueue_Status" ON "SyncQueue" ("Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413161819_AddSyncQueue', '10.0.5');

COMMIT;

