using RDO.Data.Data;
using RDO.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RDO.App.Services;

public static class EmpresaSeeder
{
    private static readonly (string Nome, string? Segmento)[] Empresas =
    {
        ("Ecompany | Piracicaba (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("DAE | Rio Claro (SP)", "Consumo"),
        ("Argo Energia | São Paulo (SP)", "Energia"),
        ("Ageplan | São Paulo (SP)", "Construção Civil"),
        ("CBC | Ribeirão Pires (SP)", "Outros"),
        ("Elemax Engenharia | Sumaré (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Cerradinho BIO | Chapadão do Céu (GO)", "Sucroalcooleiro"),
        ("Açucar Guarani | Colina (SP)", "Sucroalcooleiro"),
        ("Adama | Taquari (RS)", "Químico"),
        ("Adufertil | Jundiaí (SP)", "Fertilizantes"),
        ("ABB | Blumenau (SC)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("3M | Itapetininga (SP)", "Bens de Consumo"),
        ("3M | Sumaré (SP)", "Bens de Consumo"),
        ("AAK | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("AB Brasil | Pederneiras (SP)", "Alimentos e Bebidas"),
        ("Açucar Guarani | Olímpia (SP)", "Sucroalcooleiro"),
        ("GRU | Guarulhos (SP)", "Aeroportos"),
        ("ADM | Campo Grande (MS)", "Agroindústria"),
        ("Adata | Santo Antônio de Posse (SP)", "Bens de Consumo"),
        ("ABL | Cosmópolis (SP)", "Farmacêutico"),
        ("ADM | Uberlândia (MG)", "Agroindústria"),
        ("ACSO | Curitiba (PR)", "Metalurgia"),
        ("Aché | Cabo de Santo Agostinho (PE)", "Farmacêutico"),
        ("ADM | Porto Franco (MA)", "Agroindústria"),
        ("Adama | Londrina (PR)", "Químico"),
        ("3M | Ribeirão Preto (SP)", "Bens de Consumo"),
        ("ADM | Santos (SP)", "Agroindústria"),
        ("Adezan | Caçapava (SP)", "Embalagens"),
        ("Actemium | Contagem (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("ADM | Rondonópolis (MT)", "Agroindústria"),
        ("Adimax | Uberlândia (MG)", "Saúde e Nutrição Animal"),
        ("ADM | Descalvado (SP)", "Agroindústria"),
        ("ADM | Três Corações (MG)", "Agroindústria"),
        ("ADM | Rolim de Moura (RO)", "Agroindústria"),
        ("ADM | Paulínia (SP)", "Agroindústria"),
        ("ADM | Inhumas (GO)", "Agroindústria"),
        ("ADM | Contagem (MG)", "Agroindústria"),
        ("ADM | Canoas (RS)", "Agroindústria"),
        ("ADM | Campo Grande (MS)", "Agroindústria"),
        ("ADM | São Lourenço da Mata (PE)", "Agroindústria"),
        ("ADM | Apucarana (PR)", "Agroindústria"),
        ("ADM | Primavera do Leste (MT)", "Agroindústria"),
        ("ADM | Uberlândia 365 (MG)", "Agroindústria"),
        ("ADM | Joaçaba (SC)", "Agroindústria"),
        ("ADM | Sorriso (MT)", "Agroindústria"),
        ("Abelv Engenharia | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("ADM | Hortolândia (SP)", "Agroindústria"),
        ("ADM | Manaus (AM)", "Agroindústria"),
        ("ABB | Sorocaba (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Ambev | Nossa Sra. do Socorro (SE)", "Alimentos e Bebidas"),
        ("Dow | Rio Verde (GO)", "Agroindústria"),
        ("Boston Metal | São João Del Rei (MG)", "Metalurgia"),
        ("Air Products | Mogi das Cruzes  (SP)", "Químico"),
        ("AFSW | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Adelbras | Vinhedo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Boi Forte | Americana (SP)", "Alimentos e Bebidas"),
        ("DSM | Brotas (SP)", "Saúde e Nutrição Animal"),
        ("Bacen | Salvador (BA)", "Setor Público Financeiro"),
        ("Dayco | Indaiatuba (SP)", "Automotivo"),
        ("DMC | Araxá (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Viracopos | Campinas (SP)", "Aeroportos"),
        ("AgilEnergy | Itupeva (SP)", "Outros"),
        ("Agrale | Caxias do Sul (RS)", "Máquinas e Equipamentos Industriais"),
        ("Agrale | Caxias do Sul (RS)", "Máquinas e Equipamentos Industriais"),
        ("Agrale | Caxias do Sul (RS)", "Máquinas e Equipamentos Industriais"),
        ("Agro | Itapetininga (SP)", "Sucroalcooleiro"),
        ("Agropalma | Limeira (SP)", "Alimentos e Bebidas"),
        ("Ahlstrom | Louveira (SP)", "Papel e Celulose"),
        ("Ajinomoto | Laranjal Paulista (SP)", "Alimentos e Bebidas"),
        ("Ajinomoto | Limeira (SP)", "Alimentos e Bebidas"),
        ("Ajinomoto | Pederneiras (SP)", "Alimentos e Bebidas"),
        ("Ajinomoto | Valparaiso (SP)", "Alimentos e Bebidas"),
        ("Ajinomoto | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Alcoa Alumínio | Juruti (PA)", "Metalurgia"),
        ("Alcoa Alumínio | Poços de Caldas (MG)", "Metalurgia"),
        ("Aldoro | Rio Claro (SP)", "Químico"),
        ("Alfanews | São Paulo (SP)", "Outros"),
        ("Aliança Agrícola | Guaíra (SP)", "Sucroalcooleiro"),
        ("Aliança Engenharia | Piracicaba (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("All Test | Betim (MG)", "Outros"),
        ("Alltech | Garuva (SC)", "Máquinas e Equipamentos Industriais"),
        ("Alpargatas | João Pessoa (PB)", "Bens de Consumo"),
        ("Alpargatas | Santa Rita (PB)", "Bens de Consumo"),
        ("Alphatek | Sumaré (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Alsol | Uberlândia (MG)", "Instalação e Instalação e Montagem Industrial"),
        ("Alstom | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("AMAN | Resende (RJ)", "Outros"),
        ("Amazonas Energia | Manaus (AM)", "Energia"),
        ("Ambev | Belo Horizonte (BH)", "Alimentos e Bebidas"),
        ("Ambev | Agudos (SP)", "Alimentos e Bebidas"),
        ("Ambev | Aquiraz (CE)", "Alimentos e Bebidas"),
        ("Ambev | Brasília (DF)", "Alimentos e Bebidas"),
        ("Ambev | Cachoeiras de Macacu (RJ)", "Alimentos e Bebidas"),
        ("Ambev | Camaçari (BA)", "Alimentos e Bebidas"),
        ("Ambev | Contagem (MG)", "Alimentos e Bebidas"),
        ("Ambev | Cuiabá (MT)", "Alimentos e Bebidas"),
        ("Ambev | Curitiba (PR)", "Alimentos e Bebidas"),
        ("Ambev | Estância (SE)", "Alimentos e Bebidas"),
        ("Ambev | Goiânia (GO)", "Alimentos e Bebidas"),
        ("Ambev | Guarulhos (SP)", "Alimentos e Bebidas"),
        ("Ambev | Itapissuma (PE)", "Alimentos e Bebidas"),
        ("Ambev | Jacareí (SP)", "Alimentos e Bebidas"),
        ("Ambev | Jaguariúna (SP)", "Alimentos e Bebidas"),
        ("Ambev | João Pessoa (PB)", "Alimentos e Bebidas"),
        ("Ambev | Juatuba (MG)", "Alimentos e Bebidas"),
        ("Ambev | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("Ambev | Lages (SC)", "Alimentos e Bebidas"),
        ("Ambev | Manaus (AM)", "Alimentos e Bebidas"),
        ("Ambev | Maués (AM)", "Alimentos e Bebidas"),
        ("Ambev | Piraí (RJ)", "Alimentos e Bebidas"),
        ("Ambev | Ponta Grossa (PR)", "Alimentos e Bebidas"),
        ("Ambev | Sapucaia do Sul (RS)", "Alimentos e Bebidas"),
        ("Ambev | Teresina (PI)", "Alimentos e Bebidas"),
        ("Ambev | Uberlândia (MG)", "Alimentos e Bebidas"),
        ("Ambev | Viamão (RS)", "Alimentos e Bebidas"),
        ("Ambev | Natal (RN)", "Alimentos e Bebidas"),
        ("Ambev | Salvador (BA)", "Alimentos e Bebidas"),
        ("Ambev | Anápolis (GO)", "Alimentos e Bebidas"),
        ("Ambev | São Luís (MA)", "Alimentos e Bebidas"),
        ("Ambev | Belo Horizonte (MG)", "Alimentos e Bebidas"),
        ("Ambev | Rio de Janeiro (RJ)", "Alimentos e Bebidas"),
        ("Ambev | Jaguariúna (SP)", "Alimentos e Bebidas"),
        ("Ambev | Porto Alegre (RS)", "Alimentos e Bebidas"),
        ("Ambev | Sete Lagoas (MG)", "Alimentos e Bebidas"),
        ("Ambev | Rio de Janeiro (RJ)", "Alimentos e Bebidas"),
        ("Ambev | Manaus (AM)", "Alimentos e Bebidas"),
        ("Ambev | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Ambev | Campo Grande (RJ)", "Alimentos e Bebidas"),
        ("Aquapolo | São Paulo (SP)", "Saneamento"),
        ("Ambev | Carambeí (PR)", "Alimentos e Bebidas"),
        ("Amcor | Manaus (AM)", "Embalagens"),
        ("ArcelorMittal | Sumaré (SP)", "Siderurgia"),
        ("ArcelorMittal | Cariacica (ES)", "Siderurgia"),
        ("Amcor | Louveira (SP)", "Embalagens"),
        ("ArcelorMittal | João Monlevade (MG)", "Siderurgia"),
        ("Amcor | Jundiaí (SP)", "Embalagens"),
        ("ArcelorMittal | Juiz de Fora (MG)", "Siderurgia"),
        ("Amcor | Cabo de Santo Agostinho (PE)", "Embalagens"),
        ("ArcelorMittal | Piracicaba (SP)", "Siderurgia"),
        ("Amcor | Goiânia (GO)", "Embalagens"),
        ("ArcelorMittal | Sabará (MG)", "Siderurgia"),
        ("Amex Elétrica | São José dos Campos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("ArcelorMittal | Serra (ES)", "Siderurgia"),
        ("ABS Brasil | Campinas (SP)", "Metalurgia"),
        ("Arconvert | Jundiaí (SP)", "Papel e Celulose"),
        ("Amsted Maxion | Cruzeiro (SP)", "Metalurgia"),
        ("Arcor | Campinas (SP)", "Alimentos e Bebidas"),
        ("Amyris | Barra Bonita (SP)", "Saúde e Nutrição Animal"),
        ("Amyris | Campinas (SP)", "Alimentos e Bebidas"),
        ("Arcor | Rio das Pedras (SP)", "Alimentos e Bebidas"),
        ("Ancel | Rio Claro (SP)", "Embalagens"),
        ("Armco | Jacareí (SP)", "Metalurgia"),
        ("Andaluz | Serra (ES)", "Metalurgia"),
        ("Ambev | Manaus (AM)", "Alimentos e Bebidas"),
        ("Andritz | Araraquara (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Arosuco | Manaus (AM)", "Alimentos e Bebidas"),
        ("Art Laser | Araras (SP)", "Bens de Consumo"),
        ("Andritz | Barueri (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Asa Alumínio | Campinas (SP)", "Metalurgia"),
        ("Aspen Pharma | Serra (ES)", "Farmacêutico"),
        ("Associated Spring | Campinas (SP)", "Automotivo"),
        ("Astra | Jundaí (SP)", "Bens de Consumo"),
        ("Astros | São Paulo (SP)", "Outros"),
        ("Athié | São Paulo (SP)", "Construção Civil"),
        ("Attend Ambiental | Barueri (SP)", "Saneamento"),
        ("Audax | Vinhedo (SP)", "Químico"),
        ("Ausenco | Belo Horizonte (MG)", "Outros"),
        ("Automalógica | Jundiaí (SP)", "Outros"),
        ("Avery Dannison | Vinhedo (SP)", "Bens de Consumo"),
        ("AXION | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Axis | São Paulo (SP)", "Energia"),
        ("Baerlocher | Americana (SP)", "Químico"),
        ("Baldan | Matão (SP)", "Agroindústria"),
        ("Baldin | Pirassununga (SP)", "Sucroalcooleiro"),
        ("Ball | Jacareí (SP)", "Embalagens"),
        ("Ball | Pouso Alegre (MG)", "Embalagens"),
        ("Ball | Rio de Janeiro (RJ)", "Embalagens"),
        ("Ball | Santa Cruz (RJ)", "Embalagens"),
        ("Ball | Três Rios (RJ)", "Embalagens"),
        ("Ball | Paraguay/AS", "Embalagens"),
        ("Balluff | Vinhedo (SP)", "Eletroeletrônicos"),
        ("Bann | Paulínia (SP)", "Químico"),
        ("BASF | Guaratinguetá (SP)", "Químico"),
        ("BRF | Carambei (PR)", "Alimentos e Bebidas"),
        ("Bayer Crop | Camaçari (BA)", "Farmacêutico"),
        ("Bayer | São Paulo (SP)", "Farmacêutico"),
        ("Beadell | Pedra Branca do Amapari (AP)", "Mineração"),
        ("Bebidas Fruki | Lajeado (RS)", "Alimentos e Bebidas"),
        ("Belenus | Vinhedo (SP)", "Bens de Consumo"),
        ("Belgo | Hortolândia (SP)", "Metalurgia"),
        ("Bem Brasil | Araxá (MG)", "Alimentos e Bebidas"),
        ("Benteler | Campinas (SP)", "Automotivo"),
        ("Beraca Sabará | Itapissuma (PE)", "Químico"),
        ("Beraca Sabará | Santa Barbará D'Oeste (SP)", "Químico"),
        ("Beraca Sabará | São Paulo (SP)", "Químico"),
        ("Biancogres | Serra (ES)", "Cerâmica"),
        ("BIC | Manaus (AM)", "Bens de Consumo"),
        ("Bioenergética | Tupaciguara (MG)", "Sucroalcooleiro"),
        ("Biomin | Piracicaba (SP)", "Saúde e Nutrição Animal"),
        ("Bioritmo | São Paulo (SP)", "Infraestrutura Predial"),
        ("Birla | Cubatão (SP)", "Químico"),
        ("Frigorifico BJP | Várzea Paulista (SP)", "Alimentos e Bebidas"),
        ("Blue Sol | Ribeirão Preto (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Boehringer | Paulínia (SP)", "Farmacêutico"),
        ("Borealis | Itatiba (SP)", "Químico"),
        ("BorgWarner | Itatiba (SP)", "Automotivo"),
        ("BP Biocombustíveis | Itumbiara (GO)", "Sucroalcooleiro"),
        ("BP Bioenergia | Ituiutaba (MG)", "Sucroalcooleiro"),
        ("BP Bioenergia | Edéia (GO)", "Sucroalcooleiro"),
        ("BP Bunge | Dourados (MS)", "Sucroalcooleiro"),
        ("BR Engenharia | Araxá (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Lwarcel | Lençóis Paulista (SP)", "Papel e Celulose"),
        ("Brado Logística | Araraquara (SP)", "Transporte e Logística"),
        ("Brado Logística | Cubatão (SP)", "Transporte e Logística"),
        ("Brado Logística | Curitiba (PR)", "Transporte e Logística"),
        ("Brado Logística | Rondonópolis (MT)", "Transporte e Logística"),
        ("Brainfarma | Anápolis (GO)", "Farmacêutico"),
        ("Hypera | Barueri (SP)", "Farmacêutico"),
        ("BrasAlpla | Duque de Caxias (RJ)", "Embalagens"),
        ("BrasAlpla | Itapevi (SP)", "Embalagens"),
        ("BrasAlpla | São Paulo (SP)", "Embalagens"),
        ("BrasAlpla | Louveira (SP)", "Embalagens"),
        ("BrasAlpla | Louveira (SP)", "Embalagens"),
        ("Brasil Norte | Manaus (AM)", "Alimentos e Bebidas"),
        ("Braskem | Cubatão (SP)", "Químico"),
        ("Braskem | Mauá (SP)", "Químico"),
        ("Braskem | Paulínia (SP)", "Químico"),
        ("Braskem | Triunfo (RS)", "Químico"),
        ("Braspine | Jaguariaíva (PR)", "Bens de Consumo"),
        ("BREE | Quatro Barras (PR)", "Energia"),
        ("BRF | Concórdia (SC)", "Alimentos e Bebidas"),
        ("BRF | Campos Novos (SC)", "Alimentos e Bebidas"),
        ("BRF | Carambeí (PR)", "Alimentos e Bebidas"),
        ("BRF | Curitiba (PR)", "Alimentos e Bebidas"),
        ("BRF | Dois Vizinhos (PR)", "Alimentos e Bebidas"),
        ("BRF | Dourados (MS)", "Alimentos e Bebidas"),
        ("BRF | Jataí (GO)", "Alimentos e Bebidas"),
        ("BRF | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("BRF | Rio Verde (GO)", "Alimentos e Bebidas"),
        ("BRF | Tatuí (SP)", "Alimentos e Bebidas"),
        ("BRF | Toledo (PR)", "Alimentos e Bebidas"),
        ("BRF | Vitória de Santo Antão (PE)", "Alimentos e Bebidas"),
        ("BRF | Várzea Grande (MT)", "Alimentos e Bebidas"),
        ("BRK Ambiental | Limeira (SP)", "Saneamento"),
        ("BRK Ambiental | Sumaré (SP)", "Saneamento"),
        ("BTM | Guarulhos (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("BTM | Guarulhos (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Buaiz | Vitória (ES)", "Alimentos e Bebidas"),
        ("Buckman | Sumaré (SP)", "Químico"),
        ("BP Bunge | Cristalina (GO)", "Alimentos e Bebidas"),
        ("BP Bunge | Ponta Grossa (PR)", "Alimentos e Bebidas"),
        ("BYD | Campinas (SP)", "Automotivo"),
        ("Calmitec | Paulínia (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Canatiba | Santa Barbara D'Oeste (SP)", "Têxtil"),
        ("CAOA | Jacareí (SP)", "Automotivo"),
        ("CAOA | Anápolis (GO)", "Automotivo"),
        ("Caramuru Alimentos | Itumbiara (GO)", "Alimentos e Bebidas"),
        ("Caramuru Construções | Araraquara (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Cargill | Barreiras (BA)", "Agroindústria"),
        ("Cargill | Castro (PR)", "Agroindústria"),
        ("Cargill | Itumbiara (GO)", "Agroindústria"),
        ("Cargill | Mairinque (SP)", "Agroindústria"),
        ("Cargill | Ponta Grossa (PR)", "Agroindústria"),
        ("Cargill | Rio Verde (GO)", "Agroindústria"),
        ("Cargill | São José do Rio Pardo (SP)", "Agroindústria"),
        ("Cargill | Três Lagoas (MS)", "Agroindústria"),
        ("Cargill | Uberlândia (MG)", "Agroindústria"),
        ("Cargill | Ponta Grossa (PR)", "Agroindústria"),
        ("Cargill | Itapira (SP)", "Agroindústria"),
        ("Cargill | Ilhéus (BA)", "Agroindústria"),
        ("Cargill | Mairinque (SP)", "Agroindústria"),
        ("Cargill | Ponta Grossa (PR)", "Agroindústria"),
        ("Carta Goiás | Anápolis (GO)", "Papel e Celulose"),
        ("Cartonagem Rosni | São Paulo (SP)", "Embalagens"),
        ("Santa Filomena | Rio Claro (SP)", "Saúde e Hospitalar"),
        ("Casa dos Ventos Energias | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Castelli Consultoria | Campinas (SP)", "Outros"),
        ("Castrolanda | Castro (PR)", "Alimentos e Bebidas"),
        ("Caterpillar | Piracicaba (SP)", "Máquinas e Equipamentos Industriais"),
        ("CADAM | Almeirim (PA)", "Mineração"),
        ("Caulim da Amazônia | Vitória do Jari (AP)", "Mineração"),
        ("CBMM | Araxá (MG)", "Mineração"),
        ("CCK Automação | Curitiba (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("CEB | Brasília (DF)", "Energia"),
        ("Cebrace | Caçapava (SP)", "Bens de Consumo"),
        ("Cebrace | Jacareí (SP)", "Bens de Consumo"),
        ("Celulose Irani | Indaiatuba (SP)", "Papel e Celulose"),
        ("Celulose Nipo-Brasileira | Belo Oriente (MG)", "Papel e Celulose"),
        ("CEMIG | Belo Horizonte (MG)", "Energia"),
        ("CEMIRIM | Mogi Mirim (SP)", "Energia"),
        ("Cenergel | Poços de Caldas MG)", "Energia"),
        ("Center Norte | São Paulo (SP)", "Infraestrutura Predial"),
        ("Central Energética Moreno | Luís Antônio (SP)", "Sucroalcooleiro"),
        ("Central Energética Morrinhos | Morrinhos (GO)", "Sucroalcooleiro"),
        ("Shopping Jaraguá | Campinas (SP)", "Infraestrutura Predial"),
        ("UniMetrocamp | Campinas (SP)", "Infraestrutura Predial"),
        ("Cerâmica Cristofoletti | Rio Claro (SP)", "Cerâmica"),
        ("Cerâmica Formigres | Santa Gertrudes (SP)", "Cerâmica"),
        ("Cerâmica Embramaco | Santa Gertrudes (SP)", "Cerâmica"),
        ("Ceras Johnson | Manaus (AM)", "Químico"),
        ("CERPRO | Promissão (SP)", "Energia"),
        ("Cerradinho Bioenergia | Chapadão do Céu (GO)", "Sucroalcooleiro"),
        ("Cervejaria Bohemia | Petrópolis (RJ)", "Alimentos e Bebidas"),
        ("Cervejaria Petrópolis | Boituva (SP)", "Alimentos e Bebidas"),
        ("Cervejaria Petrópolis | Petrópolis (RJ)", "Alimentos e Bebidas"),
        ("Cervejaria Petrópolis | Teresópolis (RJ)", "Alimentos e Bebidas"),
        ("CETESB | Limeira (SP)", "Saneamento"),
        ("Cetrel | Camaçari (BA)", "Saneamento"),
        ("CFM Engenharia | Sertãozinho (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("CGC | São José dos Campos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Nestlé | Caçapava (SP)", "Alimentos e Bebidas"),
        ("Nestlé | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Vila Velha (ES)", "Alimentos e Bebidas"),
        ("Nestlé | Vila Velha (ES)", "Alimentos e Bebidas"),
        ("CIMC Raffles | Yantai/CN", "Engenharia e Gerenciamento de Projetos"),
        ("Citrosuco | Araras (SP)", "Agroindústria"),
        ("Citrosuco | Catanduva (SP)", "Agroindústria"),
        ("Citrosuco | Matão (SP)", "Agroindústria"),
        ("Civemasa | Matão (SP)", "Agroindústria"),
        ("CJ | Piracicaba (SP)", "Alimentos e Bebidas"),
        ("Clealco | Clementina (SP)", "Sucroalcooleiro"),
        ("Clealco | Penápolis (SP)", "Sucroalcooleiro"),
        ("Clealco | Queiróz (SP)", "Sucroalcooleiro"),
        ("CME Montagens | Criciúma (SC)", "Instalação e Instalação e Montagem Industrial"),
        ("CMOC | Ouvidor (GO)", "Mineração"),
        ("CMOC | Catalão (GO)", "Agroindústria"),
        ("CNPEM | Campinas (SP)", "Energia"),
        ("Coca-Cola | Cariacica (ES)", "Alimentos e Bebidas"),
        ("Coca-Cola | Rio de Janeiro (RJ)", "Alimentos e Bebidas"),
        ("Coca-Cola | Bauru (SP)", "Alimentos e Bebidas"),
        ("Coca-Cola | Campo Grande (MS)", "Alimentos e Bebidas"),
        ("Coca-Cola | Itabirito (MG)", "Alimentos e Bebidas"),
        ("Coca-Cola | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("Coca-Cola | Marília (SP)", "Alimentos e Bebidas"),
        ("Coca-Cola | Maringá (PR)", "Alimentos e Bebidas"),
        ("Coca-Cola | Mogi das Cruzes (SP)", "Alimentos e Bebidas"),
        ("Coca-Cola", "Alimentos e Bebidas"),
        ("Coca-Cola | Uberlândia (MG)", "Alimentos e Bebidas"),
        ("CODAU | Uberaba (MG)", "Saneamento"),
        ("Cofco | Catanduva (SP)", "Agroindústria"),
        ("Cofco | Rondonópolis (MT)", "Agroindústria"),
        ("Cogi | Capivari (SP)", "Metalurgia"),
        ("Colgate | São Bernardo do Campo (SP)", "Bens de Consumo"),
        ("CNEN | São Paulo (SP)", "Energia"),
        ("CBVP | Goiana (PE)", "Bens de Consumo"),
        ("CH Teles Pires | Jacareacanga (PA)", "Energia"),
        ("CHESF | Recife (PE)", "Energia"),
        ("Coca-Cola | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Nitro Química | Guarulhos (SP)", "Químico"),
        ("COPEL | Curitiba (PR)", "Energia"),
        ("CPTM | São Paulo (SP)", "Transporte e Logística"),
        ("CSN | Volta Redonda (RJ)", "Siderurgia"),
        ("Grupo Zaffari | Porto Alegre (RS)", "Infraestrutura Predial"),
        ("Shopping Dom Pedro | Campinas (SP)", "Infraestrutura Predial"),
        ("Confibra | Hortolândia (SP)", "Químico"),
        ("Connect Projetos | São José dos Campos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Consigaz | São José dos Campos (SP)", "Petróleo e Gás"),
        ("Consigma | Araras (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Consórcio Biléo Soares | Americana (SP)", "Construção Civil"),
        ("Andrade Gutierrez | São Paulo (SP)", "Construção Civil"),
        ("Construtora DELPRA | Artur Nogueira (SP)", "Construção Civil"),
        ("Contrutora TODA | São Paulo (SP)", "Construção Civil"),
        ("Continental | Camaçari (BA)", "Automotivo"),
        ("Continental | Ponta Grossa (PR)", "Automotivo"),
        ("Eaton | Porto Feliz (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Cooperativa Agraria | Ponta Grossa (PR)", "Alimentos e Bebidas"),
        ("CooperFibras | Campo Verde (MT)", "Químico"),
        ("Coorstek | Vinhedo (SP)", "Bens de Consumo"),
        ("Coorstek | São Paulo (SP)", "Bens de Consumo"),
        ("Copacol | Cafelândia (PR)", "Agroindústria"),
        ("Copebras | Cubatão (SP)", "Mineração"),
        ("Copem | São Paulo (SP)", "Outros"),
        ("Copersucar | São Paulo (SP)", "Sucroalcooleiro"),
        ("COPRA | Sumaré (SP)", "Alimentos e Bebidas"),
        ("Corning | Rio de Janeiro (RJ)", "Bens de Consumo"),
        ("Corteva | Barueri (SP)", "Agroindústria"),
        ("Cosan | Jaú (SP)", "Sucroalcooleiro"),
        ("Cosan | Aparecida de Goiânia (GO)", "Farmacêutico"),
        ("Cosan | Senador Canedo (GO)", "Farmacêutico"),
        ("Covolan | Santa Barbara D'Oeste (SP)", "Têxtil"),
        ("COZIL | Itaquaquecetuba (SP)", "Bens de Consumo"),
        ("CP Kelco | Limeira (SP)", "Químico"),
        ("CP Kelco | Matão (SP)", "Alimentos e Bebidas"),
        ("CPFL | Campinas (SP)", "Energia"),
        ("CPFL | São Paulo (SP)", "Energia"),
        ("CPFL | Campinas (SP)", "Energia"),
        ("CPIC | Capivari (SP)", "Químico"),
        ("Cristália | Cotia (SP)", "Farmacêutico"),
        ("Cristália | Itapira (SP)", "Farmacêutico"),
        ("Cristália | Pouso Alegre (MG)", "Farmacêutico"),
        ("Cristália | São Paulo (SP)", "Farmacêutico"),
        ("Croda | Campinas (SP)", "Químico"),
        ("Crown Cork | Cabreúva (SP)", "Embalagens"),
        ("Crown Cork | Rio Verde (GO)", "Embalagens"),
        ("CRS | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("CSI | Jundiaí (SP)", "Químico"),
        ("CTI Renato Archer | Campinas (SP)", "Outros"),
        ("Cummins | Guarulhos (SP)", "Máquinas e Equipamentos Industriais"),
        ("Cushman | São Paulo (SP)", "Outros"),
        ("D2 | Piracicaba (SP)", "Outros"),
        ("Dacalda | Jacarezinho (PR)", "Sucroalcooleiro"),
        ("Daisa | Embu das Artes (SP)", "Metalurgia"),
        ("Danone | Poços de Caldas (MG)", "Alimentos e Bebidas"),
        ("Danone | Poços de Caldas (MG)", "Alimentos e Bebidas"),
        ("Datacenter Services | Valinhos (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Dauper | Canela (RS)", "Alimentos e Bebidas"),
        ("Dax Energy | Mandirituba (PR)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("DBR Engenharia | Araxá (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Dedini | Piracicaba (SP)", "Metalurgia"),
        ("Dell | Hortolândia (SP)", "Eletroeletrônicos"),
        ("Delpak | Cotia (SP)", "Embalagens"),
        ("Delphi | Piracicaba (SP)", "Automotivo"),
        ("Delphi | São José dos Campos (SP)", "Automotivo"),
        ("Delta Biocombustíveis | Rio Brilhante (MS)", "Sucroalcooleiro"),
        ("Delta Construções | Rio de Janeiro (RJ)", "Construção Civil"),
        ("Delta Eletrotécnica | Sumaré (SP)", "Outros"),
        ("Delta Cerâmica | Rio Claro (SP)", "Cerâmica"),
        ("Delta Lab | Itatiba (SP)", "Farmacêutico"),
        ("Denso | Santa Barbara D'Oeste (SP)", "Automotivo"),
        ("DAE Bauru | Bauru (SP)", "Saneamento"),
        ("Destilaria Santa Capela | Santa Barbara D'Oeste (SP)", "Alimentos e Bebidas"),
        ("DHL | Embu das Artes (SP)", "Transporte e Logística"),
        ("Diatom | Mogi das Cruzes (SP)", "Mineração"),
        ("Dide | Americana (SP)", "Metalurgia"),
        ("Diesel | Hortolândia (SP)", "Petróleo e Gás"),
        ("Döhler | Limeira (SP)", "Alimentos e Bebidas"),
        ("Delphi | Gravataí (RS)", "Outros"),
        ("Donaldson | Itatiba (SP)", "Bens de Consumo"),
        ("Dori | Marília (SP)", "Alimentos e Bebidas"),
        ("Dow | Jacareí (SP)", "Agroindústria"),
        ("Dow | Hortolândia (SP)", "Agroindústria"),
        ("Dow | Jundiaí (SP)", "Químico"),
        ("Dow | Pindamonhangaba (SP)", "Químico"),
        ("DPV | Rio Claro (SP)", "Químico"),
        ("Drivetech | Sertãozinho (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Dry Color | Cosmópolis (SP)", "Químico"),
        ("DS2 Engenharia | Rio Claro (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("DSM | Mairinque (SP)", "Saúde e Nutrição Animal"),
        ("Ducoco | Linhares (ES)", "Alimentos e Bebidas"),
        ("DuPont | Itumbiara (GO)", "Agroindústria"),
        ("Duratex | Cabo de Santo Agostinho (PE)", "Bens de Consumo"),
        ("Duratex | Taquari (RS)", "Bens de Consumo"),
        ("Duratex | Uberaba (MG)", "Bens de Consumo"),
        ("EagleBurgmann | Campinas (SP)", "Outros"),
        ("EAI Engenharia | Paulínia (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Eaton | Jundiaí (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Eaton | São Paulo (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Eaton | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Eaton | Valinhos (SP)", "Automotivo"),
        ("Ecadil | Cosmópolis (SP)", "Químico"),
        ("ECOCEL | Vitória (ES)", "Engenharia e Gerenciamento de Projetos"),
        ("ECTech | Santa Barbara D'Oeste (SP)", "Energia"),
        ("EDP | São Paulo (SP)", "Energia"),
        ("EDP Smart | São Paulo (SP)", "Energia"),
        ("Edra | Ipeúna (SP)", "Metalurgia"),
        ("EGSA | Paulínia (SP)", "Bens de Consumo"),
        ("EIKO | São Paulo (SP)", "Construção Civil"),
        ("Elasa | Sumaré (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Eldorado | Três Lagoas (MS)", "Papel e Celulose"),
        ("Cargill | Uruará (PA)", "Agroindústria"),
        ("Electrolux | São Carlos (SP)", "Eletrodomésticos"),
        ("BP Bunge | Itapagipe (MG)", "Sucroalcooleiro"),
        ("BP Bunge | Santa Juliana (MG)", "Sucroalcooleiro"),
        ("BP Bunge | Frutal (MG)", "Sucroalcooleiro"),
        ("BP Bunge | Ituiutaba (MG)", "Sucroalcooleiro"),
        ("BP Bunge | Edéia (GO)", "Sucroalcooleiro"),
        ("BP Bunge | Itumbiara (GO)", "Sucroalcooleiro"),
        ("BP Bunge | Pedro Afonso (TO)", "Sucroalcooleiro"),
        ("BP Bunge | Ouroeste (SP)", "Sucroalcooleiro"),
        ("BP Bunge | Pontes Gestal (SP)", "Sucroalcooleiro"),
        ("BP Bunge | Orindiúva (SP)", "Sucroalcooleiro"),
        ("ACL Engenharia | Jundiaí (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Criativa | Florianópolis (SC)", "Engenharia e Gerenciamento de Projetos"),
        ("Cotesa | Florianópolis (SC)", "Energia"),
        ("Domínio Solar | Curitiba (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("Draw | Catalão (GO)", "Engenharia e Gerenciamento de Projetos"),
        ("Dexco | Agudos (SP)", "Cerâmica"),
        ("Cargill | Porto Ferreira (SP)", "Agroindústria"),
        ("Cargill | Bebedouro (SP)", "Agroindústria"),
        ("Canadian Solar | São Paulo (SP)", "Energia Solar"),
        ("DSM | Campinas (SP)", "Saúde e Nutrição Animal"),
        ("BP Bunge | Santa Luzia (MG)", "Alimentos e Bebidas"),
        ("Contour | São Paulo (SP)", "Energia"),
        ("Bautek | Barro Alto (GO)", "Mineração"),
        ("Baikal Construções | Aparecida de Goiânia (GO)", "Engenharia e Gerenciamento de Projetos"),
        ("Cargill | Goiânia (GO)", "Agroindústria"),
        ("Electrosol | Sumaré (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Elekeiroz | Várzea Paulista (SP)", "Químico"),
        ("Elektro | Campinas (SP)", "Energia"),
        ("Elementu | Araraquara (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Eletrodata | Campinas (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Elfusa | São João da Boa Vista (SP)", "Químico"),
        ("Elgin | Mogi das Cruzes (SP)", "Eletrodomésticos"),
        ("Alumar | São Luís (MA)", "Metalurgia"),
        ("MecNc | Contagem (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Maia e Alves | Pedro Leopoldo (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Jmarques Assessoria | Uberaba (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Luxottica | São Paulo (SP)", "Óptica"),
        ("Engesist | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Newsul | Cosmópolis (SP)", "Embalagens"),
        ("Gelita do Brasil | Maringá (PR)", "Alimentos e Bebidas"),
        ("Nexxus | Cricíuma (SC)", "Engenharia e Gerenciamento de Projetos"),
        ("Eneva | São Gonçalo do Amarante (CE)", "Energia"),
        ("Enerwatt | Santa Bárbara d'Oeste (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Energética Serranópolis | Serranópolis (GO)", "Energia"),
        ("Germed | Jaguariúna (SP)", "Farmacêutico"),
        ("Ello Painéis | Santa Bárbara d'Oeste (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Natto Alimentos | Belo Jardim (PE)", "Alimentos e Bebidas"),
        ("Luzville Engenharia | Joinville (SC)", "Engenharia Elétrica"),
        ("Mont-Engel | Botucatu (SP)", "Instalação e Montagem Industrial"),
        ("MCT Instalações | Campinas (SP)", "Instalação e Montagem Industrial"),
        ("Dioan Energia | Vitória (ES)", "Telecomunicações"),
        ("Gensep | Mirassol (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("MCM Metálurgica | Piracicaba (SP)", "Farmacêutico"),
        ("Zee-Dog | Americana (SP)", "Máquinas e Equipamentos Industriais"),
        ("KG Engenharia | Cosmópolis (SP)", "Biocombustíveis"),
        ("ESA Engenharia | Sertãozinho (SP)", "Alimentos e bebidas"),
        ("Organon | Campinas (SP)", "Construção Civil"),
        ("Grupo Navebras | Niterói (RJ)", "Automotivo"),
        ("Lumen Industrial | Campinas (SP)", "Automotivo"),
        ("KMV Engenharia | Diadema (SP)", "Mineração"),
        ("Coesia | Jundiaí (SP)", "Educação e Pesquisa"),
        ("Friato Alimentos | Pires do Rio (GO)", "Mineração"),
        ("Everynet | São Paulo (SP)", "Telecomunicações"),
        ("Mordor Projeos | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Irricom | Belo Horizonte (MG)", "Papel e Celulose"),
        ("MZT Engenharia | Mogi das Cruzes (SP)", "Automação industrial"),
        ("MRN | Oriximiná (PA)", "Instalação e Montagem Industrial"),
        ("Infoeng | Catanduva (SP)", "Energia Solar"),
        ("Akzo | Jundiaí (SP)", "Máquinas e Equipamentos Industriais"),
        ("Mahle | Mogi Guaçú (SP)", "Automação industrial"),
        ("Mahle | São Bernardo do Campo (SP)", "Infraestrutura (energia e concessões)"),
        ("Makita | Ponta Grossa (PR)", "Automotivo"),
        ("Manikraft | São Paulo (SP)", "Energia"),
        ("Mann Hummel | Indaiatuba (SP)", "Farmacêutico"),
        ("Unipac | Pompéia (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Marafon | Piracicaba (SP)", "Químico"),
        ("Grupo Marcato | Paulínia (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Marcos MEI | Cosmópolis (SP)", "Serviços administrativos"),
        ("Marilan | Marília (SP)", "Agronegócio / cooperativa"),
        ("Marilan | Igarassu (PE)", "Serviços técnicos industriais"),
        ("Martanello | Louveira (SP)", "Agronegócio / cooperativa"),
        ("Martin | Artur Nogueira (SP)", "Instrumentação elétrica / medição"),
        ("Martinrea | Monte Mor (SP)", "Indústria (manufatura geral)"),
        ("Masisa | Ponta Grossa (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Masterfoods | Guararema (SP)", "Alimentos e Bebidas"),
        ("Masterfoods | Ponta Grossa (PR)", "Alimentos e Bebidas"),
        ("Mausa | Piracicaba (SP)", "Máquinas e Equipamentos Industriais"),
        ("Maxgeo | Indaiatuba (SP)", "Outros"),
        ("MCL Manutenção | Itajubá (MG)", "Instalação e Instalação e Montagem Industrial"),
        ("Macrotécnica | Campinas (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("MD Papéis | Caieiras (SP)", "Papel e Celulose"),
        ("Medley | Brasília (DF)", "Farmacêutico"),
        ("Medley | Campinas (SP)", "Farmacêutico"),
        ("Medtronic | Ribeirão Preto (SP)", "Eletroeletrônicos"),
        ("Mefsa | Piracicaba (SP)", "Metalurgia"),
        ("MEGA Engenharia | Itaguaí (RJ)", "Engenharia e Gerenciamento de Projetos"),
        ("Megatrans | Araraquara (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Melitta | Avaré (SP)", "Alimentos e Bebidas"),
        ("Melitta | Varginha (MG)", "Alimentos e Bebidas"),
        ("Mercado Eletrônico | São Paulo (SP)", "Outros"),
        ("Mercedes-Benz | Iracemápolis (SP)", "Automotivo"),
        ("Metalfrio | São Paulo (SP)", "Eletrodomésticos"),
        ("Metalfrio | Três Lagoas (MS)", "Eletrodomésticos"),
        ("Nakayone | Cabreúva (SP)", "Metalurgia"),
        ("Metrô DF | Brasília (DF)", "Transporte e Logística"),
        ("Metrô SP | São Paulo (SP)", "Transporte e Logística"),
        ("Metso | Sorocaba (SP)", "Metalurgia"),
        ("Mexichem | Sumaré (SP)", "Químico"),
        ("Minalba | São Lourenço (MG)", "Alimentos e Bebidas"),
        ("ASB | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Minalba | Petrópolis (RJ)", "Alimentos e Bebidas"),
        ("Minas Pack | Jacutinga (MG)", "Embalagens"),
        ("Equinox Gold | Godofredo Viana (MA)", "Mineração"),
        ("Belocal Lhoist | Planaltina (GO)", "Mineração"),
        ("Curimbaba | Poços de Caldas (MG)", "Mineração"),
        ("Hydro | Paragominas (PA)", "Mineração"),
        ("Minerva | Araguaína (TO)", "Alimentos e Bebidas"),
        ("Minerva | Barretos (SP)", "Alimentos e Bebidas"),
        ("Minerva | Janaúba (MG)", "Alimentos e Bebidas"),
        ("Minerva | Mirassol D'Oeste (MT)", "Alimentos e Bebidas"),
        ("Minerva Foods | Paranatinga (MT)", "Alimentos e Bebidas"),
        ("Mogiana | Campinas (SP)", "Alimentos e Bebidas"),
        ("Moinho Cruzeiro do Sul | Rio de Janeiro (RJ)", "Alimentos e Bebidas"),
        ("Moinho Corina | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Momentive | Itatiba (SP)", "Automotivo"),
        ("Mon Ter | Itatiba (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Mondelez | Curitiba (PR)", "Alimentos e Bebidas"),
        ("Mondelez | Piracicaba (SP)", "Alimentos e Bebidas"),
        ("Mondelez | Vitória de Santo Antão (PE)", "Alimentos e Bebidas"),
        ("Mondelli | Bauru (SP)", "Alimentos e Bebidas"),
        ("Monsanto | São José dos Campos (SP)", "Agroindústria"),
        ("Mosaic | Uberaba (MG)", "Fertilizantes"),
        ("Mosaic | Araxá (MG)", "Fertilizantes"),
        ("Mosaic | Cajati (SP)", "Fertilizantes"),
        ("Mosaic | Catalão (GO)", "Fertilizantes"),
        ("Mosaic | Guará (SP)", "Fertilizantes"),
        ("Mosaic | Tapira (MG)", "Fertilizantes"),
        ("Mosaic | Uberaba (MG)", "Fertilizantes"),
        ("Mosaic | Campo Grande (MS)", "Fertilizantes"),
        ("Mosaic | Candeias (BA)", "Fertilizantes"),
        ("Mosaic | Catalão (GO)", "Fertilizantes"),
        ("Mosaic | Paraguai", "Fertilizantes"),
        ("Mosaic | Paranaguá 1 (PR)", "Fertilizantes"),
        ("Mosaic | Paranaguá 2 (PR)", "Fertilizantes"),
        ("Mosaic | Rio Grande (RS)", "Fertilizantes"),
        ("Mosaic | Rio Verde (GO)", "Fertilizantes"),
        ("Mosaic | Rondonópolis (MT)", "Fertilizantes"),
        ("Mosaic | Sorriso (MT)", "Fertilizantes"),
        ("Mosaic | Paranaguá (PR)", "Fertilizantes"),
        ("Mosaic | Patrocínio (MG)", "Fertilizantes"),
        ("Mosaic | Rosário do Catete (SE)", "Fertilizantes"),
        ("Honda | Manaus (AM)", "Automotivo"),
        ("Motorola | Jaguariúna (SP)", "Eletroeletrônicos"),
        ("MProj Engenharia | Mogi Guaçu (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("MSD | Campinas-SP", "Farmacêutico"),
        ("MSE Engenharia | Londrina (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("Multi Drive | Sumaré (SP)", "Outros"),
        ("Natural One | Jarinu (SP)", "Alimentos e Bebidas"),
        ("NBS | São Paulo (SP)", "Outros"),
        ("Neovia | Descalvado (SP)", "Agroindústria"),
        ("Nespresso | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Araraquara (SP)", "Alimentos e Bebidas, Transporte e Logística"),
        ("Nestlé | Ribeirão Preto (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Caçapava (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Águas de Santa Bárbara (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Montes Claros (MG)", "Alimentos e Bebidas"),
        ("Nestlé | Marília (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Araçatuba (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Araraquara (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Araras (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Carazinho (RS)", "Alimentos e Bebidas"),
        ("Nestlé | Cordeirópolis (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Feira de Santana (BA)", "Alimentos e Bebidas"),
        ("Nestlé | Palmeira das Missões (RS)", "Alimentos e Bebidas"),
        ("Nestlé | Rio de Janeiro (RJ)", "Alimentos e Bebidas"),
        ("Nestlé | São Bernardo do Campo (SP)", "Alimentos e Bebidas"),
        ("Nestlé | São José do Rio Pardo (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Três Rios (RJ)", "Alimentos e Bebidas"),
        ("Nestlé | Montes Claros (MG)", "Alimentos e Bebidas"),
        ("Nestlé | Araras (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Garanhuns (PE)", "Alimentos e Bebidas"),
        ("Nestlé | Goiânia (GO)", "Alimentos e Bebidas"),
        ("Nestlé | Ibiá (MG)", "Alimentos e Bebidas"),
        ("Nestlé | Itabuna (BA)", "Alimentos e Bebidas"),
        ("Nestlé | Ituiutaba (MG)", "Alimentos e Bebidas"),
        ("Nestlé | Patos de Minas (MG)", "Alimentos e Bebidas"),
        ("Nestlé | Belo Horizonte (MG)", "Alimentos e Bebidas"),
        ("Nestlé | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Ribeirão Preto (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Salvador (BA)", "Alimentos e Bebidas"),
        ("Nestlé | São Paulo (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Altinópolis (SP)", "Alimentos e Bebidas"),
        ("Nestlé | Ribeirão Preto (SP)", "Alimentos e Bebidas"),
        ("NewGen Engenharia | Guarulhos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("NG Bioenergia | Catanduva (SP)", "Sucroalcooleiro"),
        ("NG Metalúrgica | Piracicaba (SP)", "Metalurgia"),
        ("Nigro Alumínio | Araraquara (SP)", "Metalurgia"),
        ("Nilit | Americana (SP)", "Bens de Consumo"),
        ("Noble | Votuporanga (SP)", "Sucroalcooleiro"),
        ("Noja Power | Campinas (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Norske | Jaguariaíva (PR)", "Papel e Celulose"),
        ("Nouryon | Três Lagoas (MS)", "Químico"),
        ("Nova Auxiliar | Santa Barbara D'Oeste (SP)", "Embalagens"),
        ("Nova Engevix | Barueri (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Novack | Itupeva (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Novamed | Manaus (AM)", "Farmacêutico"),
        ("Novelis | Pindamonhangaba (SP)", "Metalurgia"),
        ("Novocell | Santa Bárbara d'Oeste (SP)", "Bens de Consumo"),
        ("Nuclebras | Rio de Janeiro (RJ)", "Máquinas e Equipamentos Industriais"),
        ("Ocyan | Macaé (RJ)", "Outros"),
        ("Ôhmica Engenharia | São José dos Campos (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("OJI Papéis | Piracicaba (SP)", "Papel e Celulose"),
        ("Okubo | Ribeirão Preto (SP)", "Metalurgia"),
        ("Olam | Ilhéus (BA)", "Agroindústria"),
        ("Olin | Guarujá (SP)", "Químico"),
        ("Omamori | Vinhedo (SP)", "Alimentos e Bebidas"),
        ("Omya Minerais | Cachoeiro de Itapemirim (ES)", "Mineração"),
        ("Optima | Vinhedo (SP)", "Embalagens"),
        ("Orion Carbons | Paulínia (SP)", "Químico"),
        ("Orion | São José dos Campos (SP)", "Bens de Consumo"),
        ("Orsa | Paulínia (SP)", "Papel e Celulose"),
        ("Otmix | Piracicaba (SP)", "Construção Civil"),
        ("Magnesita | Brumado (BA)", "Siderurgia, Químico"),
        ("RGTX Performance | Santa Bárbara d' Oeste (SP)", "Metalurgia"),
        ("Hemobrás | Goiana (PE)", "Farmacêutico"),
        ("Mineradora Ipe | Brumadinho (MG)", "Mineração"),
        ("Myralis | Valinhos (SP)", "Farmacêutico"),
        ("Master Energy | Campinas (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Kraf | Londrina (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("Morlan | Orlândia (SP)", "Metalurgia"),
        ("Nestlé | Araçariguama (SP)", "Alimentos e Bebidas"),
        ("Enerwatt | Goiânia (GO)", "Engenharia e Gerenciamento de Projetos"),
        ("Multilab", "Farmacêutico"),
        ("John Deere | Indaiatuba (SP)", "Indústria Pesada"),
        ("Mosaic | Palmeirante (TO)", "Fertilizantes"),
        ("Johnson | São José dos Campos (SP)", "Bens de Consumo"),
        ("General Motors | São José dos Campos (SP)", "Automotivo"),
        ("FS Biocombustíveis | Primavera do Leste (MT)", "Biocombustíveis"),
        ("Gamtal Engenharia | Piracicaba", "Engenharia e Gerenciamento de Projetos"),
        ("Gates | Jacareí (SP)", "Automotivo"),
        ("GE | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Gevisa | Campinas (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("General Chains | Piracicaba (SP)", "Metalurgia"),
        ("General Mills | Pouso Alegre (MG)", "Alimentos e Bebidas"),
        ("General Motors | Mogi das Cruzes (SP)", "Automotivo"),
        ("General Motors | São Caetano do Sul (SP)", "Automotivo"),
        ("Gerdau | Araçariguama (SP)", "Siderurgia"),
        ("Gerdau | Cotia (SP)", "Siderurgia"),
        ("Gerdau | Guarulhos (SP)", "Siderurgia"),
        ("Gerdau | São José dos Campos (SP)", "Siderurgia"),
        ("Gerdau | São Paulo (SP)", "Siderurgia"),
        ("Gerdau | São Paulo (SP)", "Siderurgia"),
        ("Gerdau | Mogi das Cruzes (SP)", "Siderurgia"),
        ("Gerdau | Pindamonhangaba (SP)", "Siderurgia"),
        ("GIMI | Suzano (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Goiasa | Goiatuba (GO)", "Sucroalcooleiro"),
        ("Golar Power | Jundiaí (SP)", "Energia"),
        ("Goodyear | Americana (SP)", "Automotivo"),
        ("Grandfood | Dourados (SP)", "Agroindústria"),
        ("Granol | Anápolis (GO)", "Agroindústria"),
        ("GRC | Campinas (SP)", "Outros"),
        ("Greenbrier Maxion | Hortolândia (SP)", "Metalurgia"),
        ("Greiner Bio-One | Americana (SP)", "Farmacêutico"),
        ("Grid Energy | Araraquara (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Grid | Itajubá (MG)", "Energia"),
        ("Boticário | São Gonçalo Dos Campos (BA)", "Bens de Consumo"),
        ("Grupo CB | Santo André (SP)", "Outros"),
        ("Tequaly | Curitiba (PR)", "Instalação e Instalação e Montagem Industrial"),
        ("Vivo Sabor | Americana (SP)", "Alimentos e Bebidas"),
        ("GTEL | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Grupo Simec | Pindamonhangaba (SP)", "Siderurgia"),
        ("H3D | Valinhos (SP)", "Outros"),
        ("Habcasa | São Paulo (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Hanesbrands | Cotia (SP)", "Têxtil"),
        ("Heineken | Araraquara (SP)", "Alimentos e Bebidas"),
        ("Heineken | Benevides (PA)", "Alimentos e Bebidas"),
        ("Heineken | Caxias (MA)", "Alimentos e Bebidas"),
        ("Heineken | Feira de Santana (BA)", "Alimentos e Bebidas"),
        ("Heineken | Gravataí (SP)", "Alimentos e Bebidas"),
        ("Heineken | Igarassu (PE)", "Alimentos e Bebidas"),
        ("Heineken | Itu (SP)", "Alimentos e Bebidas"),
        ("Heineken | Jacareí (SP)", "Alimentos e Bebidas"),
        ("Heineken | Manaus (AM)", "Alimentos e Bebidas"),
        ("Heineken | Pacatuba (CE)", "Alimentos e Bebidas"),
        ("Heineken | Ponta Grossa (PR)", "Alimentos e Bebidas"),
        ("Heineken | Recife (PE)", "Alimentos e Bebidas"),
        ("Heineken | Campos do Jordão (SP)", "Alimentos e Bebidas"),
        ("Heineken | Blumenau (SC)", "Alimentos e Bebidas"),
        ("Help Elétrica | Campinas (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Heixon | Itatiba (SP)", "Químico"),
        ("Hidromar | Cubatão (SP)", "Químico"),
        ("Hidrosan | São Carlos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("High End | Nova Odessa (SP)", "Outros"),
        ("Higident | Itajubá (MG)", "Higiene e Cosméticos"),
        ("ABB Power Grids | Guarulhos (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Hitachi | Santa Rita do Sapucaí (MG)", "Eletroeletrônicos"),
        ("Hochtief | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Honda | Sumaré (SP)", "Automotivo"),
        ("Honda Energy | Xangrila (RS)", "Energia, Automotivo"),
        ("Hospital Celso Pierro | Campinas (SP)", "Saúde e Hospitalar"),
        ("Hospital de Piracicaba | Piracicaba (SP)", "Saúde e Hospitalar"),
        ("Hummel | Tatuí (SP)", "Metalurgia"),
        ("Hydac | São Bernardo do Campo (SP)", "Metalurgia"),
        ("Hyundai | Piracicaba (SP)", "Automotivo"),
        ("Hyundai | Piracicaba (SP)", "Automotivo"),
        ("IBM | Hortolândia (SP)", "Telecomunicações"),
        ("IC Supply | Santos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("IHM Engenharia | Belo Horizonte (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Imetame | Aracruz (ES)", "Metalurgia"),
        ("Inductotherm | Indaiatuba (SP)", "Metalurgia"),
        ("Natura | Cajamar (SP)", "Bens de Consumo"),
        ("Ramenzoni | Cordeirópolis (SP)", "Papel e Celulose"),
        ("ROMI | Santa Barbara D'Oeste (SP)", "Máquinas e Equipamentos Industriais"),
        ("Inergi | Itapevi (SP)", "Outros"),
        ("Ingredion | Mogi Guaçu (SP)", "Alimentos e Bebidas"),
        ("Innovatore | São Paulo (SP)", "Outros"),
        ("Inntag | Americana (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("INPE | Cachoeira Paulista (SP)", "Infraestrutura Predial"),
        ("Install | Cotia (SP)", "Outros"),
        ("IFMG | Ouro Branco (MG)", "Infraestrutura Predial"),
        ("INPE | Cachoeira Paulista (SP)", "Outros"),
        ("Invista | Paulínia (SP)", "Bens de Consumo"),
        ("Invista | Americana (SP)", "Bens de Consumo"),
        ("Iochpe-Maxion | Contagem (MG)", "Metalurgia"),
        ("Iochpe-Maxion | Cruzeiro (SP)", "Metalurgia"),
        ("Iochpe-Maxion | Guarulhos (SP)", "Metalurgia"),
        ("Iochpe-Maxion | Limeira (SP)", "Metalurgia"),
        ("Iochpe-Maxion | Santo André (SP)", "Metalurgia"),
        ("Iochpe-Maxion | Sete Lagoas (MG)", "Metalurgia"),
        ("Ipiranga Agraindustrial | Iacanga (SP)", "Sucroalcooleiro"),
        ("Ipiranga Agroindustrial | Mococa (SP)", "Agroindústria"),
        ("Santa Casa de Limeira | Limeira (SP)", "Saúde e Hospitalar"),
        ("Refrigerantes Esportivo | Santa Barbara D'Oeste (SP)", "Alimentos e Bebidas"),
        ("IDESA | Cidade do Panamá", "Engenharia e Gerenciamento de Projetos"),
        ("JBS | Guaiçara (SP)", "Saneamento"),
        ("JBS | Jaguariúna (SP)", "Alimentos e Bebidas"),
        ("JBS | Andradina (SP)", "Alimentos e Bebidas"),
        ("JBS | Brasília (DF)", "Alimentos e Bebidas"),
        ("JBS | Cajamar (SP)", "Alimentos e Bebidas"),
        ("JBS | Cassilândia (MS)", "Alimentos e Bebidas"),
        ("JBS | Colorado do Oeste (RO)", "Alimentos e Bebidas"),
        ("JBS | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("JBS | Vilhena (RO)", "Alimentos e Bebidas"),
        ("JBS Barra do Garças | Barra do Garças (MT)", "Bens de Consumo"),
        ("JBS | Cacoal (RO)", "Alimentos e Bebidas"),
        ("JBS Campo Grande | Campo Grande (MS)", "Bens de Consumo"),
        ("JBS Cascavel | Cascavel (CE)", "Bens de Consumo"),
        ("JBS Colider | Colider (MT)", "Bens de Consumo"),
        ("JBS | Gurupi (TO)", "Alimentos e Bebidas"),
        ("JBS | Itumbiara (GO)", "Alimentos e Bebidas"),
        ("JBS | Lins (SP)", "Alimentos e Bebidas"),
        ("JBS Marabá | Marabá (PA)", "Bens de Consumo"),
        ("JBS Montenegro | Montenegro (RS)", "Bens de Consumo"),
        ("JBS Naviraí | Naviraí (MS)", "Bens de Consumo"),
        ("JBS Nova Andradina | Nova Andradina (MS)", "Bens de Consumo"),
        ("JBS Pedra Preta | Pedra Petra (MT)", "Bens de Consumo"),
        ("JBS Porangatu | Porangatu (GO)", "Bens de Consumo"),
        ("JBS | São Luís dos Montes Belos (GO)", "Alimentos e Bebidas"),
        ("JBS Uberlândia | Uberlândia (MG)", "Bens de Consumo"),
        ("JBS | São Paulo (SP)", "Alimentos e Bebidas"),
        ("JBS | Guaiçara (SP)", "Alimentos e Bebidas"),
        ("JBS | Mozarlândia (GO)", "Alimentos e Bebidas"),
        ("JBS | Jacarezinho (PR)", "Alimentos e Bebidas"),
        ("JBS | Jaguapitã (PR)", "Alimentos e Bebidas"),
        ("JBS | Lins (SP)", "Alimentos e Bebidas"),
        ("JBS | Marabá (PA)", "Alimentos e Bebidas"),
        ("JBS | Nova Andradina (MS)", "Alimentos e Bebidas"),
        ("JBS | Pedra Petra (MT)", "Alimentos e Bebidas"),
        ("JBS | Redenção (PA)", "Alimentos e Bebidas"),
        ("JBS | Rolândia (PR)", "Alimentos e Bebidas"),
        ("JBS | Barretos (SP)", "Alimentos e Bebidas"),
        ("JBS | Lins (SP)", "Alimentos e Bebidas"),
        ("JBS | Recanto das Emas (DF)", "Alimentos e Bebidas"),
        ("JBS | Guaiçara (SP)", "Alimentos e Bebidas"),
        ("JBS | Lins (SP)", "Transporte e Logística"),
        ("JCB | Sorocaba (SP)", "Máquinas e Equipamentos Industriais"),
        ("JF Automação | Goiânia (GO)", "Engenharia e Gerenciamento de Projetos"),
        ("JFS Engenharia | Araras (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("John Deere | Montenegro (RS)", "Máquinas e Equipamentos Industriais"),
        ("Johnson | Guarulhos (SP)", "Bens de Consumo"),
        ("Johnson | São José dos Campos (SP)", "Bens de Consumo"),
        ("Johnson | São José dos Campos (SP)", "Bens de Consumo"),
        ("Johnson | São José dos Campos (SP)", "Bens de Consumo"),
        ("Jonfra | Monte Mor (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Jund-Light | Jundiaí (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Karcher | Vinhedo (SP)", "Eletrodomésticos"),
        ("Kautex | Guararema (SP)", "Automotivo"),
        ("KION | Indaiatuba (SP)", "Máquinas e Equipamentos Industriais"),
        ("Klabin | Goiana (PE)", "Papel e Celulose"),
        ("Klabin | Jundiaí", "Papel e Celulose"),
        ("Klabin | Piracicaba (SP)", "Papel e Celulose"),
        ("Klabin | Rio Preto (PR)", "Papel e Celulose"),
        ("Klabin | Rio Verde (GO)", "Papel e Celulose"),
        ("Klabin | Telêmaco Borba (PR)", "Papel e Celulose"),
        ("KS Pistões | Nova Odessa (SP)", "Automotivo"),
        ("L'Occitane | Jundiaí (SP)", "Bens de Consumo"),
        ("LNLS | Campinas (SP)", "Infraestrutura Predial"),
        ("Laboratório Teuto | Anápolis (GO)", "Farmacêutico"),
        ("Allemand | Piracicaba (SP)", "Saúde e Nutrição Animal"),
        ("LD Celulose | Indianópolis (MG)", "Papel e Celulose"),
        ("LDC | Alto Araguaia (MT)", "Agroindústria"),
        ("LDC | Bebedouro (SP)", "Agroindústria"),
        ("LDC | Itumbiara (GO)", "Agroindústria"),
        ("LDC | Jataí (GO)", "Agroindústria"),
        ("LDC | Matão (SP)", "Agroindústria"),
        ("LDC | Paranavaí (PR)", "Agroindústria"),
        ("LDC | Ponta Grossa (PR)", "Agroindústria"),
        ("LDC | São Simão (GO)", "Agroindústria"),
        ("LDC | Apucarana (PR)", "Agroindústria"),
        ("LDC | Rio Verde (GO)", "Agroindústria"),
        ("LDC | São Paulo (SP)", "Agroindústria"),
        ("Leão Alimentos | Linhares (ES)", "Alimentos e Bebidas"),
        ("Leão Energia | Londrina (PR)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Lenovo | Campinas (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Libbs Farmacêutica | Embu das Artes (SP)", "Farmacêutico"),
        ("Libra Terminais | Rio de Janeiro (RJ)", "Portos"),
        ("LIG Engenharia | Pouso Alegre (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Lima e Zanette | Rio de Janeiro (RJ)", "Instalação e Instalação e Montagem Industrial"),
        ("Linear IT Engenharia | Cuiabá (MT)", "Engenharia e Gerenciamento de Projetos"),
        ("Litens | Atibaia (SP)", "Automotivo"),
        ("Lojas Renner | Rio de Janeiro (RJ)", "Bens de Consumo"),
        ("LP Sementes | Cravinhos (SP)", "Agroindústria"),
        ("Lume Cerâmica | Limeira (SP)", "Cerâmica"),
        ("Luxottica | Barueri (SP)", "Bens de Consumo"),
        ("Luxottica | Campinas (SP)", "Bens de Consumo"),
        ("Luxottica | Sumaré (SP)", "Bens de Consumo"),
        ("Lwart | Lençóis Paulista (SP)", "Bens de Consumo"),
        ("Vitarella | Jaboatão dos Guararapes (PE)", "Alimentos e Bebidas"),
        ("M Guimarães | Araras (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("M2X Engenharia | Guarulhos (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Macro Painel | Campinas (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Maex Engenharia | Santa Barbara D'Oeste (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Megal | Monte Mor (SP)", "Automotivo"),
        ("Magneti | Cabo de Santo Agostinho (PE)", "Automotivo"),
        ("Magneti | Hortolândia (SP)", "Automotivo"),
        ("Mahle | Indaiatuba (SP)", "Automotivo"),
        ("Elkem | Serra (ES)", "Químico"),
        ("Elring | Piracicaba (SP)", "Automotivo"),
        ("Elson's | Viana (ES)", "Alimentos e Bebidas"),
        ("Eltek | São José dos Campos (SP)", "Eletroeletrônicos"),
        ("ELZ Projetos | Itaguaí (RJ)", "Engenharia e Gerenciamento de Projetos"),
        ("EMA Engenharia | Campinas (SP)", "Saneamento"),
        ("Embraer | Botucatu (SP)", "Aviação"),
        ("Embraer | Gavião Peixoto (SP)", "Aviação"),
        ("Embraer | São José dos Campos (SP)", "Aviação"),
        ("Embraer | São José dos Campos (SP)", "Aviação"),
        ("Embraer | São José dos Campos (SP)", "Aviação"),
        ("Embraer | Taubaté (SP)", "Aviação"),
        ("EMMIL Engenharia | Araxá (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Correios", "Transporte e Logística"),
        ("EPTV | Campinas (SP)", "Comunicação"),
        ("EMS Pharma | Hortolândia (SP)", "Farmacêutico"),
        ("EMS Project | Campinas (SP)", "Outros"),
        ("EMX | São Paulo (SP)", "Bens de Consumo"),
        ("ENC Energy | Jundiaí (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Energisp | Americana (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Energy Substation | Itupeva (SP)", "Energia"),
        ("EnergyPlan | Rio Claro (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("EngTec Engenharia | Piracicaba (SP)", "Energia"),
        ("Engegroup | Americana (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("EngEletroseg | Araras (SP)", "Outros"),
        ("Engemon | São Paulo (SP)", "Telecomunicações"),
        ("Engepack | Simões Filhos (BA)", "Embalagens"),
        ("Enind Engenharia | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Equinix | Barueri (SP)", "Telecomunicações"),
        ("Equinox", "Mineração"),
        ("ESS Engenharia | São Caetano do Sul (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Estaleiro Ilha | Rio de Janeiro (RJ)", "Máquinas e Equipamentos Industriais"),
        ("Estaleiro Jurong | Aracruz (ES)", "Máquinas e Equipamentos Industriais"),
        ("Estre | Paulínia (SP)", "Saneamento"),
        ("Esync Energia | Sertãozinho (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Eternit | Manaus (AM)", "Bens de Consumo"),
        ("Eternit | São Paulo (SP)", "Bens de Consumo"),
        ("Etesco | Macaé (RJ)", "Petróleo e Gás"),
        ("Eucatex | Botucatu (SP)", "Bens de Consumo"),
        ("Euro-Diesel | São Paulo (SP)", "Outros"),
        ("Euroamerican | Jandira (SP)", "Transporte e Logística"),
        ("Eurochem | Serra do Salitre (MG)", "Alimentos e Bebidas"),
        ("Eurofarma | Itapevi (SP)", "Farmacêutico"),
        ("EVS | Sertãozinho (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Exercito Brasileiro | Barueri (SP)", "Outros"),
        ("Expambox | Campinas (SP)", "Móveis"),
        ("Exper Consult | Igarapé (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Expertise Engenharia | Campinas (SP)", "Construção Civil"),
        ("Extrafarma | São Luís (MA)", "Farmacêutico"),
        ("Faber-Castell | Manaus (AM)", "Bens de Consumo"),
        ("Faber-Castell | Prata (MG)", "Bens de Consumo"),
        ("Faber-Castell | São Carlos (SP)", "Bens de Consumo"),
        ("Facchini S/A | Limeira (SP)", "Metalurgia"),
        ("Faurecia | Limeira (SP)", "Automotivo"),
        ("Faurecia | Piracicaba (SP)", "Automotivo"),
        ("Faurecia | Sorocaba (SP)", "Automotivo"),
        ("Fedrigoni | Salto (SP)", "Papel e Celulose"),
        ("Feral Metalúrgica | Três Lagoas (MS)", "Metalurgia"),
        ("Fermentech | Itaquaquecetuba (SP)", "Alimentos e Bebidas"),
        ("Gedore | São Leopoldo (RS)", "Metalurgia"),
        ("Ferrero | Poços de Caldas (SP)", "Alimentos e Bebidas"),
        ("ADM | Congonhas (MG)", "Agroindústria"),
        ("Heringer | Paulínia (SP)", "Fertilizantes"),
        ("Heringer | Viana (ES)", "Fertilizantes"),
        ("Fertron | Sertãozinho (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("FG Agro | Ribeirão Preto (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Fini | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("Fiocruz | Rio de Janeiro (RJ)", "Farmacêutico"),
        ("Fitesa | Gravataí (RS)", "Outros"),
        ("FMC | Paulínia (SP)", "Agroindústria"),
        ("FMC | Uberaba (MG)", "Agroindústria"),
        ("FMC | Rio de Janeiro (RJ)", "Agroindústria"),
        ("Fockink | Panambi (RS)", "Instalação e Instalação e Montagem Industrial"),
        ("Focus | Santa Barbara D'Oeste (SP)", "Outros"),
        ("FAB | Rio de Janeiro (RJ)", "Aviação"),
        ("FourTech | Cosmópolis (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Foxconn | Jundiaí (SP)", "Eletroeletrônicos"),
        ("Frigodeliss | Capivari (SP)", "Alimentos e Bebidas"),
        ("Friuna | Piracicaba (SP)", "Alimentos e Bebidas"),
        ("FS Biocombustíveis | Lucas do Rio Verde (MT)", "Sucroalcooleiro"),
        ("FS Biocombustíveis | Sorriso (MT)", "Sucroalcooleiro"),
        ("Fundação São Francisco Xavier | Ipatinga (MG)", "Infraestrutura Predial"),
        ("Furnas | Rio de Janeiro (RJ)", "Energia"),
        ("Furnas - SE Bandeirantes | Aparecida de Goiânia (GO)", "Energia"),
        ("Galderma | Hortolândia (SP)", "Farmacêutico"),
        ("Galena | Campinas (SP)", "Farmacêutico"),
        ("GALI Energia | Bauru (SP)", "Outros"),
        ("Galvani | Angico dos Dias (BA)", "Fertilizantes"),
        ("Galvani | Luís Eduardo Magalhães (BA)", "Fertilizantes"),
        ("Galvani | Paulínia (SP)", "Fertilizantes"),
        ("Galvani Fosnor | Angico dos Dias (BA)", "Mineração"),
        ("Novaprom | Guaiçara (SP)", "Alimentos e Bebidas"),
        ("Grupo Anexo | Goiânia (GO)", "Instalação e Instalação e Montagem Industrial"),
        ("Natural One | Atibaia (SP)", "Alimentos e bebidas"),
        ("Shopping Flamboyant | Goiânia (GO)", "Infraestrutura Predial"),
        ("Orbita Eletricidade | Valinhos (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Honda | Itirapina (SP)", "Automotivo"),
        ("Usina Panorama | Itumbiara (GO)", "Sucroalcooleiro"),
        ("Syngenta | Paulínia (SP)", "Agroindústria"),
        ("Superior Industries | Rafard (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Rio-Tech", "Engenharia e Gerenciamento de Projetos"),
        ("Pakmatic | Santa Bárbara d'Oeste (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Tempo Energia | São Paulo (SP)", "Energia"),
        ("Tagna | Belo Horizonte (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Union | Barueri (SP)", "Energia"),
        ("Vulkan | Itatiba (SP)", "Outros"),
        ("Transvia Engenharia | Araxá (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("SHPX (Shopee) | Santana de Parnaíba (SP)", "Transporte e Logística"),
        ("SHPX (Shopee) | São João do Meriti (RJ)", "Transporte e Logística"),
        ("Tex Equipamentos Eletrônicos | Itupeva (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("SHPX (Shopee) | Campinas (SP)", "Transporte e Logística"),
        ("SHPX (Shopee) | Campina Grande do Sul (PR)", "Transporte e Logística"),
        ("Salton | Jarinu (SP)", "Alimentos e Bebidas"),
        ("SHPX (Shopee) | Simões Filho (BA)", "Transporte e Logística"),
        ("SHPX (Shopee) | Betim (MG)", "Transporte e Logística"),
        ("SHPX (Shopee) | Cabo de Santo Agostinho (PE)", "Transporte e Logística"),
        ("RRJ Manutenção | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("TreeTech | Atibaia (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Ridarp | Campinas (SP)", "Construção Civil"),
        ("Suzano | Ribas do Rio Pardo (MS)", "Papel e Celulose"),
        ("Volkswagen | Pacheco (AR)", "Automotivo"),
        ("Sucorrico | Araras (SP)", "Alimentos e Bebidas"),
        ("Ricamil Engenharia | Jaguariúna (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Ouro Fino Química | Uberaba (MG)", "Químico"),
        ("Ouro Fino Saúde Animal | Cravinhos (SP)", "Saúde e Nutrição Animal"),
        ("Owens-Illinois | Recife (PE)", "Embalagens"),
        ("Owens-Illinois | Vitória de Santo Antão (PE)", "Embalagens"),
        ("Oxiteno | Mauá (SP)", "Químico"),
        ("Oxiteno | Suzano (SP)", "Químico"),
        ("Oxiteno | Tremembé (SP)", "Químico"),
        ("P&Control | Americana (SP)", "Outros"),
        ("Painco | Rio das Pedras (SP)", "Metalurgia"),
        ("Papirus | Limeira (SP)", "Papel e Celulose"),
        ("Paramount Plásticos | Americana (SP)", "Embalagens"),
        ("Shopping Dom Pedro | Campinas (SP)", "Infraestrutura Predial"),
        ("PSA | Machado (MG)", "Alimentos e Bebidas"),
        ("Pastifício | Sumaré (SP)", "Alimentos e Bebidas"),
        ("Paulísta Engenharia | Campinas (SP)", "Outros"),
        ("PDCA | Campinas (SP)", "Outros"),
        ("Pepsico | Aparecida de Goiânia (GO)", "Alimentos e Bebidas"),
        ("Pepsico | Três Lagoas (MG)", "Alimentos e Bebidas"),
        ("Pepsico | Curitiba (PR)", "Alimentos e Bebidas"),
        ("Pepsico | Manaus (AM)", "Alimentos e Bebidas"),
        ("Pepsico | Sorocaba (SP)", "Alimentos e Bebidas"),
        ("Pernambuco Química | Jaboatão dos Guararapes (PE)", "Químico"),
        ("Petrocoque | Cubatão (SP)", "Petróleo e Gás"),
        ("Petrobras | São Mateus (ES)", "Petróleo e Gás"),
        ("Petrobras | Rio de Janeiro (RJ)", "Petróleo e Gás"),
        ("Petrobras | Santos (SP)", "Petróleo e Gás"),
        ("Petrobras | Paulínia (SP)", "Petróleo e Gás"),
        ("Petrobras | Cubatão (SP)", "Petróleo e Gás"),
        ("Petrobras | Vitória (SP)", "Petróleo e Gás"),
        ("Phoenix | São Paulo (SP)", "Petróleo e Gás"),
        ("Pieta.tech | Florianópolis (SC)", "Engenharia e Gerenciamento de Projetos"),
        ("Pioneer | Manaus (AM)", "Eletroeletrônicos"),
        ("Pirelli | Campinas (SP)", "Automotivo"),
        ("Pirelli | Feira de Santana (BA)", "Automotivo"),
        ("Pirelli | Gravataí (RS)", "Automotivo"),
        ("Pirelli | Santo André (SP)", "Automotivo"),
        ("Plajax | Bauru (SP)", "Químico"),
        ("Planit | Campinas (SP)", "Outros"),
        ("Beiersdorf | Campinas (SP)", "Higiene e Cosméticos"),
        ("Planmar | Sumaré (SP)", "Embalagens"),
        ("Plascar | Jundiaí (SP)", "Químico"),
        ("Plastamp | Itupeva (SP)", "Químico"),
        ("Plastek | Indaiatuba (SP)", "Químico"),
        ("Pochet | Jundiaí (SP)", "Embalagens"),
        ("Poly Play | Santa Barbara D'Oeste (SP)", "Químico"),
        ("Porto Energia | Porto Alegre (RS)", "Engenharia e Gerenciamento de Projetos"),
        ("Porto Seguro | São Paulo (SP)", "Telecomunicações"),
        ("Porto Sudeste | Itaguaí (RJ)", "Portos"),
        ("Power Solution | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Poyry Tecnologia | São Paulo (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("PPG | Sumaré (SP)", "Bens de Consumo"),
        ("P&G | Louveira (SP)", "Bens de Consumo"),
        ("P&G", "Bens de Consumo"),
        ("Produquímica | Igarassú (PE)", "Químico"),
        ("Roche | Rio de Janeiro (RJ)", "Farmacêutico"),
        ("Profarma | Maceió (AL)", "Farmacêutico"),
        ("Projetae | São Carlos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Projetize | Panambi (RS)", "Engenharia e Gerenciamento de Projetos"),
        ("Prolibrax | Santa Barbara D'Oeste (SP)", "Outros"),
        ("Prolux | Campinas (SP)", "Outros"),
        ("Prysmian | Poços de Caldas (MG)", "Construção Civil, Telecomunicações"),
        ("Prysmian | Sorocaba (SP)", "Bens de Consumo"),
        ("Pulcra | Jacareí (SP)", "Químico"),
        ("QueensBerry | Itatiba (SP)", "Alimentos e Bebidas"),
        ("Ypê | Amparo (SP)", "Bens de Consumo"),
        ("Ypê | Anápolis (GO)", "Bens de Consumo"),
        ("Raízen | Andradina (SP)", "Sucroalcooleiro"),
        ("Raízen | Capivari (SP)", "Sucroalcooleiro"),
        ("Raízen | Itabé (SP)", "Sucroalcooleiro"),
        ("Raízen | Valparaiso (SP)", "Sucroalcooleiro"),
        ("Raízen | Piracicaba (SP)", "Energia"),
        ("Raízen | Guariba (SP)", "Sucroalcooleiro"),
        ("Raízen | Piracicaba (SP)", "Sucroalcooleiro"),
        ("Realcafé | Viana (ES)", "Alimentos e Bebidas"),
        ("Reckitt Benckiser | São Paulo (SP)", "Bens de Consumo"),
        ("Rede D'Or | São Paulo (SP)", "Saúde e Hospitalar"),
        ("Renault | Curitiba (PR)", "Automotivo"),
        ("Renner | Cajamar (SP)", "Químico"),
        ("Renuka | Promissão (SP)", "Sucroalcooleiro"),
        ("Rhodia | Itatiba (SP)", "Químico"),
        ("Rhodia | Paulínia (SP)", "Químico"),
        ("Riclan | Rio Claro (SP)", "Alimentos e Bebidas"),
        ("RIMA Industrial | Pirapora (MG)", "Mineração, Siderurgia"),
        ("RIMA Industrial | Várzea da Palma (MG)", "Metalurgia"),
        ("Coca-Cola | Duque de Caxias (RJ)", "Alimentos e Bebidas"),
        ("Risatec | Itapevi (SP)", "Papel e Celulose"),
        ("Bosch | Campinas (SP)", "Automotivo"),
        ("Bosch | Curitiba (PR)", "Automotivo"),
        ("Bosch | Itupeva (SP)", "Automotivo"),
        ("Rockwell | São Paulo (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Rolls Royce | Rio de Janeiro (RJ)", "Automotivo"),
        ("Romanato | Várzea Paulista (SP)", "Alimentos e Bebidas"),
        ("Rossi | Rio de Janeiro (RJ)", "Construção Civil"),
        ("Rousselot | Presidente Epitácio (SP)", "Alimentos e Bebidas"),
        ("Rowag | Catalão (GO)", "Engenharia e Gerenciamento de Projetos"),
        ("Royal FIC | Paulínia (SP)", "Petróleo e Gás"),
        ("RTE Rodonaves | Americana (SP)", "Transporte e Logística"),
        ("S&R Energy | Americana (SP)", "Outros"),
        ("SABESP | São Paulo (SP)", "Saneamento"),
        ("Saint-Gobain | Barra Mansa (RJ)", "Metalurgia"),
        ("Saint-Gobain | São Caetano do Sul (SP)", "Bens de Consumo"),
        ("Saint-Gobain | Sobradinho (DF)", "Outros"),
        ("Saint-Gobain | Sumaré (SP)", "Bens de Consumo"),
        ("Saint-Gobain | Vinhedo (SP)", "Bens de Consumo"),
        ("Sales | São Paulo (SP)", "Outros"),
        ("Samarco | Belo Horizonte (MG)", "Mineração"),
        ("Samarco | Ouro Fino (MG)", "Mineração"),
        ("Samarco | Vitória (ES)", "Mineração"),
        ("Samsung | Campinas (SP)", "Eletroeletrônicos"),
        ("Sanasa | Campinas (SP)", "Saneamento"),
        ("Sanofi | Suzano (SP)", "Farmacêutico"),
        ("Santa Helena | Ribeirão Preto (SP)", "Alimentos e Bebidas"),
        ("Santher | Bragança Paulista (SP)", "Papel e Celulose"),
        ("Santista | Americana (SP)", "Têxtil"),
        ("Santista | Aracajú (SE)", "Têxtil"),
        ("Santista | Paulista (PE)", "Têxtil"),
        ("Santo Antônio Energia | Porto Velho (RO)", "Engenharia e Gerenciamento de Projetos"),
        ("Santo Antônio Energia | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("São José Agroindustrial | Igarassu (PE)", "Agroindústria"),
        ("Sara Lee | Jundiaí (SP)", "Alimentos e Bebidas"),
        ("SATEL Brasil | Rio de Janeiro (RJ)", "Engenharia e Gerenciamento de Projetos"),
        ("SBM | Santos (SP)", "Petróleo e Gás"),
        ("Scania | São Bernardo do Campo (SP)", "Automotivo"),
        ("Schaeffler | Sorocada (SP)", "Metalurgia"),
        ("Schneider | Blumenau (SC)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Schneider | São Paulo (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Scholle | Vinhedo (SP)", "Embalagens"),
        ("Sealed Air | Jaguariúna (SP)", "Bens de Consumo"),
        ("SEC Power | Diadema (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Semp Toshiba | Manaus (AM)", "Eletroeletrônicos"),
        ("Sempre Sementes", "Agroindústria"),
        ("Sener | São Paulo (SP)", "Energia, Construção Civil, Outros"),
        ("Serya | Araxá (MG)", "Alimentos e Bebidas"),
        ("Sew Eurodrive | Indaiatuba (SP)", "Bens de Consumo"),
        ("SHELL | Rio de Janeiro (RJ)", "Petróleo e Gás"),
        ("Sherwin-Williams | Sumaré (SP)", "Bens de Consumo"),
        ("Shopping Iguatemi | Campinas (SP)", "Infraestrutura Predial"),
        ("Siemens | Jundiaí (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Sima Engenharia | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Sincroniza | Pinhais (PR)", "Outros"),
        ("Siner Engenharia | Carapicuíba (SP)", "Energia"),
        ("Sipcam | Uberaba (MG)", "Agroindústria"),
        ("Sistechne | Curitiba (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("Skanska | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("SKF | Cajamar (SP)", "Bens de Consumo"),
        ("Solbras | São João Da Boa Vista (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Sony | Manaus (AM)", "Eletroeletrônicos"),
        ("SOS Service | Santana de Parnaíba (SP)", "Outros"),
        ("Springer Carrier | Manaus (AM)", "Eletrodomésticos"),
        ("Black&Decker | Uberaba (MG)", "Bens de Consumo"),
        ("Stara | Não Me Toque (RS)", "Agroindústria"),
        ("Starrett | Itu (SP)", "Bens de Consumo"),
        ("Stihl | São Leopoldo (RS)", "Bens de Consumo"),
        ("STK Sistemas | Curitiba (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("Subsea 7 | Niterói (RJ)", "Engenharia e Gerenciamento de Projetos"),
        ("Cutrale | Araraquara (SP)", "Agroindústria"),
        ("Cutrale | Colina (SP)", "Agroindústria"),
        ("Cutrale | Conchal (SP)", "Agroindústria"),
        ("Cutrale | Guarujá (SP)", "Agroindústria"),
        ("Cutrale | Itápolis (SP)", "Agroindústria"),
        ("Cutrale | Santos (SP)", "Agroindústria"),
        ("Cutrale | Uchoa (SP)", "Agroindústria"),
        ("Sultan | Itaquaquecetuba (SP)", "Têxtil"),
        ("Sulzer | Jundiaí (SP)", "Bens de Consumo"),
        ("Sun Coke East | Serra (ES)", "Petróleo e Gás"),
        ("Suzano | Aracruz (ES)", "Papel e Celulose"),
        ("Suzano | Imperatriz (MA)", "Papel e Celulose"),
        ("Suzano | Jacareí (SP)", "Papel e Celulose"),
        ("Suzano | Limeira (SP)", "Papel e Celulose"),
        ("Suzano | Suzano (SP)", "Papel e Celulose"),
        ("Suzano | Três Lagoas (MS)", "Papel e Celulose"),
        ("Syngenta | Itápolis (SP)", "Agroindústria"),
        ("Syngenta | Holambra (SP)", "Agroindústria"),
        ("Syngenta São Paulo | São Paulo (SP)", "Agroindústria"),
        ("Syngenta | Formosa (GO)", "Agroindústria"),
        ("Syngenta | Holambra (SP)", "Agroindústria"),
        ("Syngenta | Ituiutaba (MG)", "Agroindústria"),
        ("Syngenta Seeds | Lucas do Rio Verde (MT)", "Agroindústria"),
        ("Syngenta | Matão (SP)", "Agroindústria"),
        ("Syngenta | Uberlândia (MG)", "Agroindústria"),
        ("Synthes | Rio Claro (SP)", "Metalurgia"),
        ("Takeda | Jaguariúna (SP)", "Farmacêutico"),
        ("TASA Tinturaria | Americana (SP)", "Têxtil"),
        ("Tebroek | Sorocaba (SP)", "Outros"),
        ("TECMON | Goiânia (GO)", "Instalação e Instalação e Montagem Industrial"),
        ("Tecnovolt | Vila Velha (ES)", "Outros"),
        ("TEKA | Artur Nogueira (SP)", "Têxtil"),
        ("Tepx | Osasco (SP)", "Saneamento"),
        ("Termelétrica Pernambuco III | Igarassu (PE)", "Energia"),
        ("Termium | Santa Cruz (RJ)", "Mineração"),
        ("Terra Azul | Nova Odessa (SP)", "Químico"),
        ("Tesla Eletricidade e Mecânica | Sete Lagoas (MG)", "Automotivo"),
        ("Tessler Engenharia | São Paulo (SP)", "Construção Civil"),
        ("Tetra Pak | Monte Mor (SP)", "Embalagens"),
        ("Thyssenkrupp | Campo Limpo Paulista (SP)", "Metalurgia"),
        ("Tigre | Rio Claro (SP)", "Bens de Consumo"),
        ("TMD Friction | Indaiatuba (SP)", "Automotivo"),
        ("Toyota | Indaiatuba (SP)", "Automotivo"),
        ("Toyota | Porto Feliz (SP)", "Automotivo"),
        ("Toyota | São Bernardo do Campo (SP)", "Automotivo"),
        ("Toyota | Sorocaba (SP)", "Automotivo"),
        ("Trafocamp | Campinas (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Tramontina | Recife (PE)", "Bens de Consumo"),
        ("Tramontina | Farroupilha (RS)", "Bens de Consumo"),
        ("Transmiservice | Sertãozinho (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("EXAL Brasil | Itupeva (SP)", "Embalagens"),
        ("Trop Frutas | Linhares (ES)", "Alimentos e Bebidas"),
        ("Ultra Hi | Barueri (SP)", "Químico"),
        ("Umicore | Americana (SP)", "Químico"),
        ("Unilever | Indaiatuba (SP)", "Bens de Consumo"),
        ("Unilever | Suape (PE)", "Bens de Consumo"),
        ("Unilever | Valinhos (SP)", "Bens de Consumo"),
        ("Unilever | Vinhedo (SP)", "Bens de Consumo"),
        ("Unilever | Jaboatão dos Guararapes (PE)", "Alimentos e Bebidas"),
        ("Unipar Carbocloro | Cubatão (SP)", "Químico"),
        ("Unipar Carbocloro, Solvay | Santo André (SP)", "Químico"),
        ("Unicamp | Campinas (SP)", "Infraestrutura Predial"),
        ("Usiminas Mecânica | Ipatinga (MG)", "Siderurgia"),
        ("Usina Furlan | Santa Bárbara d'Oeste (SP)", "Sucroalcooleiro"),
        ("Usina Batatais | Batatais (SP)", "Sucroalcooleiro"),
        ("Usina Boa Vista | Quirinópolis (GO)", "Sucroalcooleiro"),
        ("Usina Colorado | Guaíra (SP)", "Sucroalcooleiro"),
        ("Usina Iracema | Iracemápolis (SP)", "Sucroalcooleiro"),
        ("Usina Lins | Lins (SP)", "Sucroalcooleiro"),
        ("Usina Monte Alegre | Monte Belo (MG)", "Sucroalcooleiro"),
        ("Usina Nova Gália | Paraúna (GO)", "Sucroalcooleiro"),
        ("Usina Ouroeste | Ouroeste (SP)", "Sucroalcooleiro"),
        ("Usina Rio Dourado | Cachoeira Dourada (GO)", "Sucroalcooleiro"),
        ("Usina Santa Adélia | Jaboticabal (SP)", "Sucroalcooleiro"),
        ("Usina Santa Adélia | Pereira Barreto (SP)", "Sucroalcooleiro"),
        ("Usina Santa Adélia | Sud Mennucci (SP)", "Sucroalcooleiro"),
        ("Usina Santa Cruz | Américo Brasiliense (SP)", "Sucroalcooleiro"),
        ("Usina Santa Cruz | Américo Brasiliense (SP)", "Sucroalcooleiro"),
        ("Usina Santa Elisa | Sertãozinho (SP)", "Sucroalcooleiro"),
        ("Usina Santa Fé | Nova Europa (SP)", "Sucroalcooleiro"),
        ("Usina Santa Helena | Santa Helena de Goiás (GO)", "Sucroalcooleiro"),
        ("Usina Santa Vitória | Santa Vitória (MG)", "Sucroalcooleiro"),
        ("Usina Santo Ângelo | Pirajuba (MG)", "Sucroalcooleiro"),
        ("Usina São Francisco | Quirinópolis (GO)", "Sucroalcooleiro"),
        ("Usina São João | Araras (SP)", "Sucroalcooleiro"),
        ("Usina Estiva | Novo Horizonte (SP)", "Sucroalcooleiro"),
        ("Usina São Luiz | Ourinhos (SP)", "Sucroalcooleiro"),
        ("Usina São Martinho | Pradópolis (SP)", "Sucroalcooleiro"),
        ("Usina Uberaba | Uberaba (MG)", "Sucroalcooleiro"),
        ("Usiminas | Guarulhos (SP)", "Siderurgia"),
        ("Usiminas | Betim (MG)", "Siderurgia"),
        ("Usiminas | Campo Limpo Paulista (SP)", "Siderurgia"),
        ("Usiminas | Ipatinga (MG)", "Siderurgia"),
        ("Usiminas | Itatiaiuçu (MG)", "Siderurgia"),
        ("Usiminas | Porto Alegre (RS)", "Siderurgia"),
        ("Usiminas | Santa Luzia (MG)", "Siderurgia"),
        ("Usiminas | Suape (PE)", "Siderurgia"),
        ("UTE Pecém | São Gonçalo do Amarante (CE)", "Energia"),
        ("Utility Engenharia | Campinas (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Vale do Verdão | Turvelândia (GO)", "Sucroalcooleiro"),
        ("Vale Ourilândia do Norte | Ourilândia do Norte (PA)", "Mineração"),
        ("Vale | São Luis do Maranhão (MA)", "Mineração"),
        ("Vale | Vitória (ES)", "Portos"),
        ("Vale Energia", "Energia"),
        ("Valeant | Indaiatuba (SP)", "Farmacêutico"),
        ("Valeo | Campinas (SP)", "Automotivo"),
        ("Valmont | São João da Boa Vista (SP)", "Energia"),
        ("Vebratec | São Paulo (SP)", "Outros"),
        ("Vepan | Itaquaquecetuba (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("Vidroporto | Porto Ferreira (SP)", "Embalagens"),
        ("Villares Metals | Sumaré (SP)", "Siderurgia"),
        ("Villas Boas | Eusébio (CE)", "Farmacêutico"),
        ("Vitopel | Votorantim (SP)", "Químico"),
        ("Vitória | Valinhos (SP)", "Bens de Consumo"),
        ("Voith | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Volga Engenharia | Aparecida de Goiânia (GO)", "Instalação e Instalação e Montagem Industrial"),
        ("Volkswagen | São Carlos (SP)", "Automotivo"),
        ("Volkswagen | São Paulo (SP)", "Automotivo"),
        ("Volvo | Curitiba (PR)", "Automotivo"),
        ("Vorbe Engenharia | Goiânia (GO)", "Outros"),
        ("Votorantim | Corporativo", "Cimentos"),
        ("Votorantim | Poty Paulista (PE)", "Cimentos"),
        ("Votorantim | Recife (PE)", "Cimentos"),
        ("Votorantim | Vidal Ramos (SC)", "Cimentos"),
        ("Votorantim Cimentos | Salto de Pirapora (SP)", "Cimentos"),
        ("Votorantim | São Paulo (SP)", "Energia"),
        ("Votorantim | Alumínio (SP)", "Siderurgia"),
        ("Votorantim | Guarulhos (SP)", "Siderurgia"),
        ("Votorantim", "Energia"),
        ("VP | São José do Rio Pardo (SP)", "Instalação e Instalação e Montagem Industrial"),
        ("VSM Industrial | Canas (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("WABCO | Campinas (SP)", "Automotivo"),
        ("WB Manutenção | Três Lagoas (MS)", "Engenharia e Gerenciamento de Projetos"),
        ("WEG | Blumenau (SC)", "Bens de Consumo"),
        ("WEG Jaraguá do Sul | Jaraguá do Sul (SC)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("WEG | Linhares (ES)", "Bens de Consumo"),
        ("WEG | São Paulo (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("WestRock | Araçatuba (SP)", "Papel e Celulose"),
        ("WestRock | Blumenau (SC)", "Papel e Celulose"),
        ("WestRock | Pacajus (CE)", "Papel e Celulose"),
        ("WestRock | Porto Feliz (SP)", "Papel e Celulose"),
        ("WestRock | Três Barras (SC)", "Papel e Celulose"),
        ("WestRock | Campinas (SP)", "Papel e Celulose"),
        ("Whirlpool | Rio Claro (SP)", "Eletrodomésticos"),
        ("White Martins | Paulínia (SP)", "Químico"),
        ("Wickbold | Hortolândia (SP)", "Alimentos e Bebidas"),
        ("Wilson Sons | Rio de Janeiro (RJ)", "Portos, Transporte e Logística"),
        ("Wipro | Piracicaba (SP)", "Outros"),
        ("Wirex Cable | Santa Branca (SP)", "Bens de Consumo"),
        ("Woobo | Piracicaba (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("World Fix | Campinas (SP)", "Saúde e Hospitalar"),
        ("WWGF Refrigeração | São José dos Campos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("XYPD Embalagens | Conchas (SP)", "Embalagens"),
        ("Yara Fertilizantes | Cubatão (SP)", "Fertilizantes"),
        ("Yara Fertilizantes | Ponta Grossa (RS)", "Fertilizantes"),
        ("Yara Fertilizantes | Portol Alegre (RS)", "Fertilizantes"),
        ("Zanarotti Projetos | Dumont (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Zanini Renk | Cravinhos (SP)", "Máquinas e Equipamentos Industriais"),
        ("Zanotti | Jaraguá do Sul (SC)", "Bens de Consumo"),
        ("Zaraplast | São Paulo (SP)", "Embalagens"),
        ("ZBN Fundição | Araçatuba (SP)", "Metalurgia"),
        ("Zemar | Navegantes (SC)", "Máquinas e Equipamentos Industriais"),
        ("Zettatecck | Araras (SP)", "Outros"),
        ("ZF | Limeira (SP)", "Automotivo"),
        ("ZF | Sorocaba (SP)", "Automotivo"),
        ("SIG | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Pec Energia | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Technique Engenharia | Porto Alegre (RS)", "Engenharia e Gerenciamento de Projetos"),
        ("Volkswagen | São Bernardo do Campo (SP)", "Automotivo"),
        ("Ypê | Salto (SP)", "Químico"),
        ("WMartins | Orlândia (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("PCM Engenharia | Belo Horizonte (MG)", "Mineração"),
        ("OZ Minerals | Curianópolis (PA)", "Mineração"),
        ("Sel | Campinas (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("RIMA Industrial | Capitão Enéas (MG)", "Metalurgia"),
        ("Saga | São Paulo (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Unicamp | Campinas (SP)", "Educação e Pesquisa"),
        ("Vale | Corporativo", "Mineração"),
        ("Ypê | Itajubá (MG)", "Produtos de limpeza"),
        ("Verallia | Jacutinga (MG)", "Embalagens"),
        ("Suzano | Mucuri (BA)", "Papel e Celulose"),
        ("SIG | Campo Largo (PR)", "Engenharia e Gerenciamento de Projetos"),
        ("Prima Foods | Cassilândia (MS)", "Alimentos e Bebidas"),
        ("Prima Foods | Araguari (MG)", "Alimentos e Bebidas"),
        ("Prima Foods | Santa Fé de Goiás (GO)", "Alimentos e Bebidas"),
        ("Sonoco | Araras (SP)", "Embalagens"),
        ("Yamaha | Manaus (AM)", "Automotivo"),
        ("Sendi Engenharia | Bauru (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Sylvamo | Mogi Guaçu (SP)", "Papel e Celulose"),
        ("International Paper | Três Lagoas (MS)", "Papel e Celulose"),
        ("EPCM | Americana (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("PHS Automações | São José dos Campos (SP)", "Automação industrial"),
        ("Singapura | Vinhedo (SP)", "Instalação e Montagem Industrial"),
        ("Viena Engenharia | Uberlândia (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Vetek | Piracicaba (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Villares Metals | Flores da Cunha (RS)", "Siderurgia"),
        ("Brasol LTDA | São Paulo (SP)", "Energia Solar"),
        ("Upton | Santana de Parnaíba (SP)", "Máquinas e Equipamentos Industriais"),
        ("Asas Automação | Uberaba (MG)", "Automação industrial"),
        ("GrupoIter | Rio de Janeiro (RJ)", "Infraestrutura de energia"),
        ("Bunge | Luziânia (GO)", "Alimentos e Nutrição Animal"),
        ("Usina da Mata | Valparaíso (SP)", "Sucroalcooleiro"),
        ("ABB | Água Branca (SP)", "Fabricação de Equipamentos Elétricos e Eletrônicos"),
        ("Seg Automotive | Itupeva (SP)", "Automotivo"),
        ("TSE | Goiânia (GO)", "Energia"),
        ("Geolab | Anápolis (GO)", "Farmacêutico"),
        ("JCI do Brasil | São José dos Campos (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("DSM | Barra do Garça (MT)", "Saúde e Nutrição Animal"),
        ("Farquar Engenharia | Porto Velho (RO)", "Engenharia e Gerenciamento de Projetos"),
        ("Vallor | Uberaba (MG)", "Engenharia e Gerenciamento de Projetos"),
        ("Chlorum Solution | Igarassu (PE)", "Químico"),
        ("ADM | Apucarana (PR)", "Agroindústria"),
        ("Guidotti Engenharia | Conchal (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Soltec | Lauro de Freitas (BA)", "Energia Solar"),
        ("Soltec | Lauro de Freitas (BA)", "Energia"),
        ("Ronilson Serviços Administrativos | São Paulo (SP)", "Serviços administrativos"),
        ("Copagril | Marechal Candido Rondon (PR)", "Agronegócio"),
        ("MMV Serviços Técnicos | São Paulo (SP)", "Serviços técnicos industriais"),
        ("Copagril | Marechal Cândido Rondon (PR)", "Agronegócio"),
        ("Nansen | Campinas (SP)", "Instrumentação elétrica / medição"),
        ("Fareva | Louveira (SP)", "Indústria (manufatura geral)"),
        ("Neoacqua | Araquari (SC)", "Saneamento"),
        ("Pemon | Iperó (SP)", "Construção Civil"),
        ("Kubix | Indaiatuba (SP)", "Agronegócio"),
        ("Tyconnex | Atibaia (SP)", "Engenharia e Gerenciamento de Projetos"),
        ("Luxottica | Barueri (SP)", "Bens de Consumo"),
    };

    public static void Seed(RdoDbContext db)
    {
        var nomesExistentes = new HashSet<string>(
            db.Empresas.Select(e => e.Nome), StringComparer.OrdinalIgnoreCase);

        bool alterado = false;
        foreach (var (nome, _) in Empresas)
        {
            if (nomesExistentes.Contains(nome)) continue;

            db.Empresas.Add(new Empresa
            {
                Nome = nome,
                IsActive = true,
                UpdatedAt = DateTime.UtcNow,
            });
            alterado = true;
        }

        if (alterado) db.SaveChanges();
    }
}